<?php if($this->pageCount) : ?>
<ul class="pagination">
    <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>><a href="<?php echo $this->url('materials', array('action' => 'category', 'id' => $this->category->getId(),'page' => $this->previous)); ?>">«</a></li>
    <?php foreach ($this->pagesInRange as $page): ?>
        <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('materials', array('action' => 'category', 'id' => $this->category->getId(),'page' => $page)); ?>">
                <?php echo $page; ?>
            </a></li>
    <?php endforeach; ?>
    <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>><a href="<?php echo $this->url('materials', array('action' => 'category', 'id' => $this->category->getId(),'page' => $this->next)); ?>">»</a></li>
</ul>
<?php endif; ?>