<nav id="sidenav" class="classlist">
    <?php $user = $this->identity(); ?>
    <?php if (!$user) $user = new \AmaUsers\Entity\User(); ?>

    <?php echo $this->navigation()
        ->menu('category_navigation')
        ->setMinDepth(0)
        ->setMaxDepth(0)
        ->setPartial('partial/category-menu-li'); ?>

    <?php if($user->hasRole('admin')) : ?>
        <?php if($this->category) : ?>
            <a href="javascript:;" class="btn btn-default" onclick="silmaring.openInModal('<?php echo $this->url('categories', array('action' => 'edit', 'id' => $this->category->getId())); ?>')"><?php echo $this->translate("Edit selected category"); ?></a>
            <a href="javascript:;" class="btn btn-default add-child-category" onclick="silmaring.openInModal('<?php echo $this->url('categories', array('action' => 'add', 'id' =>  $this->category->getId())); ?>')"><?php echo $this->translate("Add child category"); ?></a>
        <?php else : ?>
            <a href="javascript:;" class="btn btn-default" onclick="silmaring.openInModal('<?php echo $this->url('categories', array('action' => 'add')); ?>')"><?php echo $this->translate("Add main category"); ?></a>
        <?php endif; ?>
        <!--
        <a href="javascript:;" class="btn btn-default margin-top-10" onclick="silmaring.openInModal('<?php echo $this->url('categories', array('action' => 'import')); ?>')"><?php echo $this->translate("Import categories from xls"); ?></a>
        -->
        <div class="clear"></div>
        <br/>
    <?php endif; ?>

    <?php if(!$user->hasRole('admin')) :?>
    <?php echo $this->navigation()
        ->menu('normal_navigation')
        ->setMinDepth(0)
        ->setMaxDepth(0)
        ->setPartial('partial/normal-menu-li'); ?>
    <?php endif; ?>

    <?php if($user->hasRole('admin')) :?>
        <?php echo $this->navigation()
            ->menu('admin_navigation')
            ->setMinDepth(0)
            ->setMaxDepth(0)
            ->setPartial('partial/admin-menu-li'); ?>
    <?php endif; ?>
    <?php if($user->hasRole('school')) :?>
        <?php echo $this->navigation()
            ->menu('single_school_navigation')
            ->setMinDepth(0)
            ->setMaxDepth(0)
            ->setPartial('partial/admin-menu-li'); ?>
    <?php endif; ?>

</nav>

