<?php $this->headTitle($this->translate("Add school")); ?>
<header class="page-head clearfix">
<h1><?php echo $this->translate("Add school"); ?></h1>
</header>
<div clas="row">
    <div class="col-md-12">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('schools', array('action' => 'add')));
        $form->setAttribute('role', 'form');
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('enctype', 'multipart/form-data');
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <?php if ($this->successMessages) : ?>
        <?php foreach ($this->successMessages as $message) : ?>
            <div class="alert alert-success">
                <?php echo $message; ?>
            </div>
        <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($this->messages) : ?>
        <div class="alert alert-warning">
            <?php echo $this->messages; ?>
        </div>
        <?php endif; ?>
        <?php if (!empty($this->errorMessages)) : ?>
        <div class="alert alert-warning">
            <?php foreach ($this->errorMessages as $message) : ?>
                <?php echo $message; ?>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
            <div class="col-sm-6">
                <?php echo $this->formElement($form->get('name')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('shortName')); ?>
            <div class="col-sm-6">
                <?php echo $this->formElement($form->get('shortName')); ?>
            </div>
        </div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('status')); ?>
            <div class="col-sm-1 pull-left">
                <?php echo $this->formElement($form->get('status')->setValue(1)); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-3">
                <?php echo $this->formButton($form->get('submit'), $this->translate('Add')); ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>