<?=$this->headTitle($this->translate('Search'));?>
<header class="page-head clearfix">
<h1><?=$this->translate('Search results');?> (<?=$this->materialsCount;?>)</h1>
</header>
<div id="content">
    <?php if($this->materialsCount==0 && $this->termLength>2) : ?>
    <div class="alert alert-warning"><?=$this->translate('No results where found!');?></div>
    <?php endif; ?>
    <?php if($this->termLength<2) : ?>
        <div class="alert alert-warning"><?=$this->translate('Search term must be atleast 2 characters long!');?></div>
    <?php endif; ?>
    <ul class="lesson_plan search">
        <?php foreach($this->materials as $cid => $material) :?>
            <li>
                        <?php if(!$this->uploads()->has($material['filename']) && $material['file_type']!='video' && $material['file_type']!='test') continue; ?>
                        <?php $sentClasses = $this->em->getRepository('AmaMaterials\Entity\File')->findFilesSentToClasses($this->user, $material['file_id']); ?>
                        <?php
                        $target = 'target="_blank"';
                        $onclick = '';
                        if ( $material['file_type'] == 'image' || $material['file_type']=='file' ) {
                            $url = $this->uploads()->get($material['filename']);
                            $ext = $url->getExtension();
                            if($material['file_type']=='image') {
                                $url = $this->htImgUrl($material['filename'], 'images1024x768');
                            }
                        }
                        else if($material['file_type']=='video') {
                            $url = $material['file_video'];
                        }
                        else if($material['file_type']=='test') {
                            $url = 'javascript:;';
                            $target = '';
                            $onclick = "onclick=\"silmaring.openInModal('".$this->url('manageTests', array('action' => 'edit', 'cid' => $cid, 'id' => $material['file_id']))."','modal-lg');\"";
                            if(count($sentClasses)>0) {
                                $onclick = "onclick=\"silmaring.openInModal('".$this->url('manageTests', array('action' => 'no-edit', 'cid' => $cid, 'id' => $material['file_id']))."','modal-lg');\"";
                            }
                        }
                        ?>
                        <a href="<?php echo $url; ?>" <?=$target;?> <?=$onclick;?>><?php echo $material['name']; ?></a> <?php if($this->getIsNew($material['date_added']) && $this->user->hasRole('k_student')) : ?><span class="new_item">(<?php echo $this->translate('NEW'); ?>)</span><?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>