<?php if(isset($this->category)) $this->headTitle($this->category->getName()); ?>
<div id="content">
    <ul class="lesson_plan">
        <?php foreach($this->materials as $cid => $materialsArray) :?>
            <li>
                <h2 class="underline_title">
                    <?php $categoryPath = $this->getCategoryPath($this->allCategories, $cid); $categoryPath = array_reverse($categoryPath); ?>
                    <?php $i = 1; foreach($categoryPath as $category) : ?>
                        <?php if($i!=1) : ?> / <?php endif; ?>
                        <?php if($i==2) : ?><span class="semi_b"><?php endif; ?>
                        <?php if($i>2) : ?><span class="simple"><?php endif; ?>
                        <?php echo $category['c_name']; ?>
                        <?php if($i>2) : ?></span><?php endif; ?>
                        <?php if($i==2) : ?></span><?php endif; ?>
                        <?php $i++; endforeach; ?>
                </h2>
                <ol>
                    <?php foreach($materialsArray as $material) :?>
                        <?php if(!$this->uploads()->has($material['filename']) && $material['file_type']!='video' && $material['file_type']!='test'  && $material['file_type']!='worksheet') continue; ?>
                        <?php
                        $target = 'target="_blank"';
                        $onclick = '';
                        if ( $material['file_type'] == 'image' || $material['file_type']=='file' ) {
                            $url = $this->uploads()->get($material['filename']);
                            $ext = $url->getExtension();
                            if($material['file_type']=='image') {
                                $url = $this->htImgUrl($material['filename'], 'images1024x768');
                            }
                            $onclick = "onclick=\"silmaring.addViewed('" . $this->url('materials', array('action' => 'view', 'id' => $material['id'], 'page' => $material['fileclass_id'])) . "');\"";
                        }
                        else if($material['file_type']=='video') {
                            $url = $material['file_video'];
                            $onclick = "onclick=\"silmaring.addViewed('" . $this->url('materials', array('action' => 'view', 'id' => $material['id'], 'page' => $material['fileclass_id'])) . "');\"";
                        }
                        else if($material['file_type']=='test') {
                            $url = 'javascript:;';
                            $target = '';
                            $onclick = "onclick=\"silmaring.openInModal('".$this->url('solveTests', array('action' => 'index', 'id' => $material['id'], 'fid' => $material['fileclass_id']))."','modal-lg');\"";
                            if($material['allreadyDoneTest']>0){
                                $onclick = "onclick=\"silmaring.openInModal('".$this->url('solveTests', array('action' => 'solved', 'id' => $material['id'], 'fid' => $material['fileclass_id']))."','modal-lg');\"";
                            }
                        }
                        else if($material['file_type']=='worksheet') {
                            $url = 'javascript:;';
                            $target = '';
                            $onclick = "onclick=\"silmaring.openInModal('".$this->url('solveWorksheets', array('action' => 'index', 'id' => $material['id'], 'fid' => $material['fileclass_id']))."','modal-lg');\"";
                            if($material['allreadyDoneWorksheet']>0){
                                $onclick = "onclick=\"silmaring.openInModal('".$this->url('solveWorksheets', array('action' => 'solved', 'id' => $material['id'], 'fid' => $material['fileclass_id']))."','modal-lg');\"";
                            }
                        }
                        ?>
                        <li><a href="<?php echo $url; ?>"  <?=$target;?> <?=$onclick;?>><?php echo $material['name']; ?></a> <?php if($this->getIsNew($material['date_added'])) : ?><span class="new_item">(<?php echo $this->translate('NEW'); ?>)</span> <?php if($material['allreadyDoneTest']>0 || $material['allreadyDoneWorksheet']>0) : ?>(<?=$this->translate("Allready done")?>)<?php endif; ?><?php endif; ?></li>
                    <?php endforeach; ?>
                </ol>
               <?php if($this->isParentCategory) : ?> <a href="<?php echo $this->url('dashboard', array('action' => 'category', 'id' => $cid)); ?>" class="btn btn-default"><?php echo $this->translate("View all"); ?></a> <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>