<div class="tab_block clearfix question_block" id="question0">
    <input type="hidden" name="questionNr" value="0" class="questionNr">
    <input type="hidden" name="question_element[0][answerType]" value="2" class="answerType">
    <ul class="nav nav-pills nav-stacked col-sm-1">
        <li class="active"><a href="#tab_a_0" data-type="2" data-toggle="pill" onclick="silmaringTest.cleanAnswerInputs($(this))"><i class="test-type test-check"></i></a></li>
        <li><a href="#tab_b_0"  data-type="1" data-toggle="pill"  onclick="silmaringTest.cleanAnswerInputs($(this))"><i class="test-type test-txt"></i></a></li>
        <li><a href="#tab_c_0"  data-type="3" data-toggle="pill" onclick="silmaringTest.cleanAnswerInputs($(this))"><i class="test-type test-number"></i></a></li>
    </ul>
    <div class="tab-content col-sm-11">
        <?php $collections = $form->get('question_element'); ?>
        <?php foreach($collections as $col) :?>
            <div class="tab-pane" id="tab_b_0">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <?= $this->formElement($col->get('question')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                        <div class="col-sm-1">
                            <?= $this->formElement($col->get('points')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                        <span class="form_inline_txt"><?= $this->translate($col->get('points')->getLabel()) ?></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 add_images">
                        <div class="row">
                        </div>
                        <div class="progress" id="progress0" style="display:none;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                            </div>
                        </div>
                        <a class="add_item add_image" href="javascript:;"><input type="file" data-nr="0" name="image" onchange="silmaringTest.createImageThumb($(this))" /><i class="add_item_ico">+</i> <?= $this->translate('Add image'); ?></a>
                    </div>
                </div>

                <h4><?= $this->translate('Answer'); ?></h4>

                <div class="answers-block">
                    <div class="checkbox"><label><?= $this->formElement($col->get('mustContainWords')->setValue(0)->setAttribute('disabled','disabled')); ?> <?= $this->translate($col->get('mustContainWords')->getLabel()) ?></label></div>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-sm-6">
                                <?= $this->formElement($col->get('words')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="tab-pane-footer clearfix">
                    <div class="pull-right">
                        <a href="#" class="move_item"><?= $this->translate('Move'); ?> <i class="glyphicon glyphicon-fullscreen"></i></a>
                        <a href="javascript:;" onclick="silmaringTest.deleteQuestion($(this))" class="remove_item"><?= $this->translate('Delete'); ?>  <i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </div>
            </div>

            <div class="tab-pane active" id="tab_a_0">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <?= $this->formElement($col->get('question')->setValue('')->setAttribute('disabled', null)); ?>
                        </div>
                        <div class="col-sm-1">
                            <?= $this->formElement($col->get('points')->setValue('')->setAttribute('disabled', null)); ?>
                        </div>
                        <span class="form_inline_txt"><?= $this->translate($col->get('points')->getLabel()) ?></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 add_images">
                        <div class="row">
                        </div>
                        <div class="progress" id="progress0" style="display:none;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                            </div>
                        </div>
                        <a class="add_item add_image" href="javascript:;"><input type="file" data-nr="0" name="image" onchange="silmaringTest.createImageThumb($(this))" /><i class="add_item_ico">+</i> <?= $this->translate('Add image'); ?></a>
                    </div>
                </div>

                <h4><?= $this->translate('Answer'); ?></h4>

                <div class="answers-block">
                    <?php $collection2 = $col->get('answer_option_element'); ?>
                    <?php foreach($collection2 as $col2) :?>
                        <div class="checkbox clearfix with_input single_option">
                            <label class="pull-left with_label">
                                <?=$this->formInput($col2->get('rightAnswer')->setValue(1)->setAttribute('disabled', null)->setAttribute('type', 'checkbox')->setAttribute("onclick", "silmaringTest.setRightAnswer($(this), $(this).parent().parent().parent().parent())")); ?>
                                <span><?= $this->translate($col2->get('rightAnswer')->getLabel()) ?></span>
                            </label>
                            <div class="col-sm-5">
                                <?= $this->formElement($col2->get('option')->setValue('')->setAttribute('disabled', null)); ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="tab-pane-footer clearfix">
                    <div class="pull-left">
                        <a href="javascript:;" class="add_item" onclick="silmaringTest.addOption($(this));"><i class="add_item_ico">+</i> <?= $this->translate('Add option'); ?></a>
                    </div>
                    <div class="pull-right">
                        <a href="#" class="move_item"><?= $this->translate('Move'); ?> <i class="glyphicon glyphicon-fullscreen"></i></a>
                        <a href="javascript:;" onclick="silmaringTest.deleteQuestion($(this))" class="remove_item"><?= $this->translate('Delete'); ?>  <i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="tab_c_0">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <?= $this->formElement($col->get('question')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                        <div class="col-sm-1">
                            <?= $this->formElement($col->get('points')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                        <span class="form_inline_txt"><?= $this->translate($col->get('points')->getLabel()) ?></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 add_images">
                        <div class="row">
                        </div>
                        <div class="progress" id="progress0" style="display:none;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                            </div>
                        </div>
                        <a class="add_item add_image" href="javascript:;"><input type="file" data-nr="0" name="image" onchange="silmaringTest.createImageThumb($(this))" /><i class="add_item_ico">+</i> <?= $this->translate('Add image'); ?></a>
                    </div>
                </div>
                <h4><?= $this->translate('Answer'); ?></h4>

                <div class="answers-block">
                <?php $i = 1; foreach($collection2 as $col3) : ?>
                    <?php if($i>1) continue; ?>
                    <div class="checkbox clearfix with_input">
                        <label class="pull-left with_label">
                            <?=$this->formInput($col3->get('rightAnswer')->setValue(1)->setAttribute('type', 'radio')->setAttribute('disabled', 'disabled')->setAttribute("onclick", "silmaringTest.setRightAnswer($(this), $(this).parent().parent().parent().parent())")); ?><span><?= $this->translate($col3->get('rightAnswer')->getLabel()) ?></span>
                        </label>
                        <div class="col-sm-4">
                            <?= $this->formElement($col3->get('option')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                    </div>

                    <div class="checkbox clearfix with_input">
                        <label class="pull-left with_label">
                            <?= $this->formInput($col3->get('rightRange')->setValue(1)->setAttribute('disabled', 'disabled')->setAttribute("onclick", "silmaringTest.setRightAnswer($(this), $(this).parent().parent().parent().parent())")); ?><span><?= $this->translate($col3->get('rightRange')->getLabel()) ?></span>
                        </label>
                        <div class="col-sm-4">
                            <?= $this->formElement($col3->get('option')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                        <span class="pull-left"><?= $this->translate("to"); ?></span>
                        <div class="col-sm-4">
                            <?= $this->formElement($col3->get('optionTwo')->setValue('')->setAttribute('disabled', 'disabled')); ?>
                        </div>
                    </div>
                    <?php $i++; ?>
                <?php endforeach; ?>
                </div>

                <div class="tab-pane-footer clearfix">
                    <div class="pull-right">
                        <a href="#" class="move_item"><?= $this->translate('Move'); ?> <i class="glyphicon glyphicon-fullscreen"></i></a>
                        <a href="javascript:;" onclick="silmaringTest.deleteQuestion($(this))" class="remove_item"><?= $this->translate('Delete'); ?>  <i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div><!-- tab content -->
</div><!-- question-block -->