<?php

$answers = $this->question->getAnswers();
$aType = $this->question->getAnswerType();
$singleAnswer = $answers[0];
$secondSingleAnswer = $answers[1];
if( isset($singleAnswer) && $singleAnswer->getOptionTwo() ) {
    $secondSingleAnswer = $singleAnswer;
    unset($singleAnswer);
}
?>

<div class="tab_block clearfix question_block" id="question<?=$this->qnr;?>">
    <input type="hidden" name="questionNr" value="<?=$this->qnr;?>" class="questionNr">
    <input type="hidden" name="question_element[<?=$this->qnr;?>][answerType]" value="<?=$aType?>" class="answerType">
    <input type="hidden" name="question_element[<?=$this->qnr;?>][questionId]" value="<?=$this->question->getId()?>">
    <ul class="nav nav-pills nav-stacked col-sm-1">
        <li <?php if($aType==2) : ?>class="active"<?php endif; ?>><a  href="#tab_a_<?=$this->qnr;?>" data-type="2" data-toggle="pill"><i class="test-type test-check"></i></a></li>
        <li <?php if($aType==1) : ?>class="active"<?php endif; ?>><a  href="#tab_b_<?=$this->qnr;?>" data-type="1" data-toggle="pill"><i class="test-type test-txt"></i></a></li>
        <li <?php if($aType==3) : ?>class="active"<?php endif; ?>><a  href="#tab_c_<?=$this->qnr;?>"   data-type="3" data-toggle="pill"><i class="test-type test-number"></i></a></li>
    </ul>
    <div class="tab-content col-sm-11">
        <?php $collections = $form->get('question_element'); ?>
        <?php foreach($collections as $col) :?>
            <div class="tab-pane <?php if($aType==1) : ?>active<?php endif; ?>" id="tab_b_<?=$this->qnr;?>">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <?=$this->customFormElement($col->get('question')->setValue($this->question->getQuestion())->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                        </div>
                        <div class="col-sm-1">
                            <?= $this->customFormElement($col->get('points')->setValue($this->question->getPoints())->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                        </div>
                        <span class="form_inline_txt"><?= $this->translate($col->get('points')->getLabel()) ?></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 add_images">
                        <div class="row">
                            <?php foreach($question->getImages(  ) as $image) : ?>
                                <?=$this->partial('ama-tests/partial/image-thumb', array('questionNr' => $this->gnr, 'filename' => $image->getFilename(), 'imageId' => $image->getId(), 'question' => $this->question, 'disable' => true));?>
                            <?php endforeach; ?>
                        </div>
                        <div class="progress" id="progress<?=$this->qnr;?>" style="display:none;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                            </div>
                        </div>
                    </div>
                </div>

                <h4><?= $this->translate('Answer'); ?></h4>
                <div class="answers-block">
                    <div class="checkbox"><label><?=$this->customFormElement($col->get('mustContainWords')->setValue($this->getDbValue($singleAnswer, 'getMustContainWords'))->setAttribute('disabled',  'disabled'), $this->qnr); ?> <?= $this->translate($col->get('mustContainWords')->getLabel()) ?></label></div>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-sm-6">
                                <?= $this->customFormElement($col->get('words')->setValue($this->getDbValue($singleAnswer, 'getWords'))->setAttribute('disabled',  'disabled'), $this->qnr); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="tab-pane-footer clearfix">
                 </div>
            </div>

            <div class="tab-pane <?php if($aType==2) : ?>active<?php endif; ?>" id="tab_a_<?=$this->qnr;?>">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <?= $this->customFormElement($col->get('question')->setValue($this->question->getQuestion())->setAttribute('disabled',  'disabled'), $this->qnr); ?>
                        </div>
                        <div class="col-sm-1">
                            <?= $this->customFormElement($col->get('points')->setValue($this->question->getPoints())->setAttribute('disabled','disabled'), $this->qnr); ?>
                        </div>
                        <span class="form_inline_txt"><?= $this->translate($col->get('points')->getLabel()) ?></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 add_images">
                        <div class="row">
                            <?php foreach($question->getImages() as $image) : ?>
                                <?=$this->partial('ama-tests/partial/image-thumb', array('questionNr' => $this->gnr, 'filename' => $image->getFilename(), 'imageId' => $image->getId(), 'question' => $this->question, 'disable' => true));?>
                            <?php endforeach; ?>
                        </div>
                        <div class="progress" id="progress0" style="display:none;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                            </div>
                        </div>
                    </div>
                </div>

                <h4><?= $this->translate('Answer'); ?></h4>

                <div class="answers-block">
                    <?php
                    $collection2 = $col->get('answer_option_element');
                    $answersList = $answers;
                    ?>
                    <?php $i = 0; foreach($collection2 as $key => $col2) :?>
                        <div class="checkbox clearfix with_input single_option">
                            <label class="pull-left with_label">
                                <?= $this->customFormElement($col2->get('rightAnswer')->setValue($this->getDbValue($answersList[$i], 'getIsRight', 0))->setAttribute('type', 'checkbox')->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                                <span><?= $this->translate($col2->get('rightAnswer')->getLabel()) ?></span>
                            </label>
                            <div class="col-sm-5">
                                <?= $this->customFormElement($col2->get('option')->setValue($this->getDbValue($answersList[$i], 'getOption'))->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                            </div>
                        </div>
                        <?php unset($answersList[$i]); $i++; ?>
                    <?php endforeach; ?>
                    <?php foreach($answersList as  $answer) :?>
                        <div class="checkbox clearfix with_input single_option">
                            <label class="pull-left with_label">
                                <?= $this->customFormElement($col2->get('rightAnswer')->setValue($answer->getIsRight())->setAttribute('type', 'checkbox')->setAttribute('disabled', 'disabled'), $this->qnr, $i); ?>
                                <span><?= $this->translate($col2->get('rightAnswer')->getLabel()) ?></span>
                            </label>
                            <div class="col-sm-5">
                                <?= $this->customFormElement($col2->get('option')->setValue($answer->getOption())->setAttribute('disabled', 'disabled'), $this->qnr, $i); ?>
                            </div>
                        </div>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                </div>
                <div class="tab-pane-footer clearfix">
                </div>
            </div>
            <div class="tab-pane <?php if($aType==3) : ?>active<?php endif; ?>" id="tab_c_<?=$this->qnr;?>">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <?= $this->customFormElement($col->get('question')->setValue($this->question->getQuestion())->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                        </div>
                        <div class="col-sm-1">
                            <?= $this->customFormElement($col->get('points')->setValue($this->question->getPoints())->setAttribute('disabled',  'disabled'), $this->qnr); ?>
                        </div>
                        <span class="form_inline_txt"><?= $this->translate($col->get('points')->getLabel()) ?></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 add_images">
                        <div class="row">
                            <?php foreach($question->getImages() as $image) : ?>
                                <?=$this->partial('ama-tests/partial/image-thumb', array('questionNr' => $this->gnr, 'filename' => $image->getFilename(), 'imageId' => $image->getId(), 'question' => $this->question, 'disable' => true));?>
                            <?php endforeach; ?>
                        </div>
                        <div class="progress" id="progress0" style="display:none;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                            </div>
                        </div>
                    </div>
                </div>
                <h4><?= $this->translate('Answer'); ?></h4>

                <div class="answers-block">
                    <?php $i = 1; foreach($collection2 as $col3) : ?>
                        <?php if($i>1) continue; ?>
                        <div class="checkbox clearfix with_input">
                            <label class="pull-left with_label">
                                <?= $this->customFormInput($col3->get('rightAnswer')->setValue(1)->setAttribute('type', 'radio')->setAttribute('disabled', 'disabled')->setAttribute("onclick", "silmaringTest.setRightAnswer($(this), $(this).parent().parent().parent().parent())")->setAttribute('checked', ($this->getDbValue($singleAnswer, 'getIsRight', 0)==1?'checked':'')), $this->qnr); ?><span><?= $this->translate($col3->get('rightAnswer')->getLabel()) ?></span>
                            </label>
                            <div class="col-sm-4">
                                <?= $this->customFormElement($col3->get('option')->setValue($this->getDbValue($singleAnswer, 'getOption'))->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                            </div>
                        </div>

                        <div class="checkbox clearfix with_input">
                            <label class="pull-left with_label">
                                <?= $this->customFormInput($col3->get('rightRange')->setValue(1)->setAttribute('disabled', 'disabled')->setAttribute("onclick", "silmaringTest.setRightAnswer($(this), $(this).parent().parent().parent().parent())")->setAttribute('checked', $this->getDbValue($secondSingleAnswer, 'getIsRight', 0)?'checked':''), $this->qnr); ?><span><?= $this->translate($col3->get('rightRange')->getLabel()) ?></span>
                            </label>
                            <div class="col-sm-4">
                                <?= $this->customFormElement($col3->get('option')->setValue($this->getDbValue($secondSingleAnswer, 'getOption'))->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                            </div>
                            <span class="pull-left"><?= $this->translate("to"); ?></span>
                            <div class="col-sm-4">
                                <?= $this->customFormElement($col3->get('optionTwo')->setValue($this->getDbValue($secondSingleAnswer, 'getOptionTwo'))->setAttribute('disabled', 'disabled'), $this->qnr); ?>
                            </div>
                        </div>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                </div>

                <div class="tab-pane-footer clearfix">
                </div>
            </div>
        <?php endforeach; ?>
    </div><!-- tab content -->
</div><!-- question-block -->