<?=$this->headTitle($this->translate('Statistics'));?>
<header class="page-head clearfix">
    <h1><?=$this->translate("Statistics");?></h1>
</header>
<script src="<?=$this->url('home');?>/js/Chart.min.js"></script>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#cmy" role="tab" data-toggle="tab"><strong><?=$this->translate('My statistics')?></strong></a></li>
    <?php foreach($this->classes as $class) : ?>
    <li><a href="#c<?=$class['c_id'];?>" role="tab" data-toggle="tab" onclick="silmaring.loadStatisticsTabView('<?=$this->url('statistics', array('action' => 'tab'))?>', <?=$class['c_id'];?>)"><strong><?=$class['c_className'];?> (<?=$class['s_shortName']?>)</strong></a></li>
    <?php endforeach; ?>
</ul>
<!-- Tab panes -->
<div class="tab-content">
<div class="tab-pane active" id="cmy">
    <br/>
    <h2><?=$this->translate("Online time");?></h2>
    <br/>
    <div class="canvas_wrap col-sm-9 daily_wrap">
        <span class="canvas_top_label"><?=$this->translate("Hours");?></span>
        <span class="canvas_bottom_right_label"><?=$this->translate("Days");?></span>
        <canvas id="dailymy" width="570" height="300"></canvas>
        <script>
            <?php $hoursCount = count($this->hours); ?>
            var dailymy = {
                labels : [<?php for($i=1;$i<=$this->daysInMonth;$i++)  echo ($i!=1?",":"") . $i; ?>],
                datasets : [
                    {
                        label: "<?=$this->translate('Statistics');?>",
                        fillColor : "rgba(163,195,209,0.6)",
                        strokeColor : "rgba(163,195,209,1)",
                        responsive: true,
                        data : [<?php for($i=1;$i<=$hoursCount;$i++)  echo ($i!=1?",":"") . $this->hours['hour' . $i]; ?>]
                    }
                ]
            }
            var dailymy_a = document.getElementById('dailymy').getContext('2d');
            new Chart(dailymy_a).Bar(dailymy);
        </script>
    </div>
    <div class="canvas_wrap col-sm-9 weekly_wrap" style="display:none">
    </div>
    <div class="canvas_wrap col-sm-9 monthly_wrap" style="display:none">
    </div>
    <div class="col-sm-3">
        <div class="radio">
            <label>
                <input type="radio" name="type" checked="checked" id="daily" value="daily" onclick="silmaring.loadStatisticsView('<?=$this->url('statistics', array('action' => 'type'));?>','daily', 'my')"> <?=$this->translate("Day");?>
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="type" id="weekly" value="weekly" onclick="silmaring.loadStatisticsView('<?=$this->url('statistics', array('action' => 'type'));?>','weekly', 'my')"> <?=$this->translate("Week");?>
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="type" id="monthly" value="monthly" onclick="silmaring.loadStatisticsView('<?=$this->url('statistics', array('action' => 'type'));?>','monthly', 'my')"> <?=$this->translate("Month");?>
            </label>
        </div>
    </div>
</div>
<?php foreach($this->classes as $class) : ?>
<div class="tab-pane" id="c<?=$class['c_id'];?>">
</div>
<?php endforeach; ?>
<script>
    var loadingHtml = '<div class="loading text-center" style="display:block;"><img src="<?php echo $this->url('home'); ?>images/ajax-loader.gif" alt="" /></div>';
</script>
