<span class="canvas_top_label"><?=$this->translate("Hours");?></span>
<span class="canvas_bottom_right_label"><?=$this->translate("Weeks");?></span>
<canvas id="<?=$this->type;?><?=$this->class_id?>" width="590" height="300"></canvas>
<script>
    <?php
        $daysInMonthCount = count($this->daysInMonth)-1;
     ?>
    var <?=$this->type;?><?=$this->class_id?> = {
        labels : [<?php for($i=0;$i<=$daysInMonthCount;$i++)  echo ($i!=0?",":"") . '"' . $this->translate('Week') . ' ' . $this->daysInMonth[$i] . '"'; ?>],
            datasets : [
            {
                label: "<?=$this->translate('Statistics');?>",
                fillColor : "rgba(163,195,209,0.6)",
                strokeColor : "rgba(163,195,209,1)",
                responsive: true,
                data : [<?php for($i=0;$i<=$daysInMonthCount;$i++)  echo ($i!=0?",":"") . $this->hours['hour' . $this->daysInMonth[$i]]; ?>]
            }
        ]
    }
    var <?=$this->type;?><?=$this->class_id?>_a = document.getElementById('<?=$this->type;?><?=$this->class_id?>').getContext('2d');
    new Chart(<?=$this->type;?><?=$this->class_id?>_a).Bar(<?=$this->type;?><?=$this->class_id?>);
</script>