<div class="modal fade" id="modalPopup" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog modal-vertical-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2><?php echo $this->translate("Loading..."); ?></h2>
            </div>
            <div class="modal-body">
                 <img src="<?php echo $this->url("home"); ?>images/ajax-loader.gif" alt="loading" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate("Sulge aken");?></button>
            </div>
        </div>
    </div>
</div>
<script>
    var dataTablesLang = '<?=$this->url('home');?>languages/dataTables.et.txt';
</script>
<?php
        echo $this->inlineScript()->prependFile($this->basePath('/min?g=js'));
?>
<script>
    var loginUrl = '<?php echo $this->url('login'); ?>';
    var ajaxLoader = "<?php echo $this->url("home"); ?>images/ajax-loader.gif";
    var ajaxLoaderTitle = "<?php echo $this->translate("Loading..."); ?>";
    <?php if($this->identity()) : ?>
    silmaring.checkAlerts('<?php echo $this->url("checkAlerts"); ?>');
    $(function(){setInterval("silmaring.checkAlerts('<?php echo $this->url("checkAlerts"); ?>')", 20000); }); //20 seconds
    <?php endif; ?>
</script>

<?php if($this->login == 1) : ?>
<script>
    $(function(){
        <?php if($this->type == 'form') : ?>
             $('#login button').trigger('click');
        <?php endif; ?>
        <?php if($this->type == 'facebook') : ?>
            $('#facebookLogin')[0].click();
        <?php endif; ?>
        <?php if($this->type == 'google') : ?>
            $('#googleLogin')[0].click();
        <?php endif; ?>
    });
</script>
<?php endif; ?>
</body>
</html>