<?php echo $this->partial('layout/header.phtml'); ?>
<body class="<?php if ( $this->currentRoute() == 'dashboard' ) : ?>welcome-screen<?php endif; ?>">
<div id="wrapper">
    <?php echo $this->partial('layout/navbar-header.phtml'); ?>
    <div class="container-fluid">
        <?php echo $this->partial('layout/menu.phtml'); ?>
        <div class="row">
            <div class="main">
                <?php echo $this->content; ?>
            </div>
        </div>
    </div>
    <?php echo $this->partial('layout/footer.phtml'); ?>
