<?php
	$form = $this->form;
	$form->setAttribute('id', 'editDescriptionForm');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id')->setValue($courseId));
?>

<div class="form-group">
	<?php echo $this->formRow($form->get('description')); ?>
</div>
<div class="form-group">
	<a href="<?php echo $this->url('teacher/edit-description', array('id' => $courseId)) ?>" id="submitEditDesc">Muuda</a>
</div>

<?php echo $this->form()->closeTag(); ?>

