<?php
	$this->headTitle('Kodutöö - ');
?>
<div class="row">

		<h2>Kodutöö</h2>

</div>
<div class="row">
	<p class="well"><?php echo $this->escapeHtml($homework->description) ?></p>
</div>
<?php if (!empty($homework->url)) { ?>

	<a class="btn btn-default btn-sm" href="<?php echo $this->escapeHtml($homework->url) ?>" target="_blank" download>Lae kodutöö alla</a>

<?php } ?>

<a class="btn btn-default btn-sm" href="<?php echo $this->url('teacher/edit-homework', array('id' => $homework->id)) ?>">Muuda kodutööd</a>