<?php
	$this->headTitle('Kursus - ');
?>

<h2><?php echo $this->escapeHtml($courseData['course']->name) ?></h2>
<hr>
<div class="row">
	<?php echo $this->sidebar ?>
	<div class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title pull-left">Kirjeldus</h2>
				<!-- <a class="btn btn-primary btn-sm pull-right" id="editDesctiption" href="<?php echo $this->url('teacher/edit-description', array('id' => $course->id)) ?>">
					<span class="glyphicon glyphicon-pencil"></span>
					Muuda
				</a> -->
				<div class="clearfix"></div>
			</div>
			<div class="panel-body" id="courseDescription">
				<p>
					<?php echo $courseData['course']->description ?>
				</p>
			</div>
		</div>
		<br>
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title pull-left">Teemad</h2>
				<a class="btn btn-primary btn-sm pull-right" id="addSubject" href="<?php echo $this->url('teacher/add-subject', array('id' => $courseData['course']->id)) ?>">
					<span class="glyphicon glyphicon-plus"></span>
					Lisa uus teema
				</a>
				<div class="clearfix"></div>
			</div>
			<ul class="list-group" id="subjects">
				<?php foreach ($courseData['subjects'] as $subject): ?>
					<li class="list-group-item active" id="subjectId<?php echo $subject['id'] ?>">
						<p class="subjectName"><?php echo $this->escapeHtml($subject['name']) ?></p>
						<div class="btn-group" role="group" aria-label="...">
							<a class="btn btn-default btn-xs editSubject" href="<?php echo $this->url('teacher/edit-subject', array('id' => $subject['id'])) ?>">
								<span class="glyphicon glyphicon-pencil"></span>
							</a>
							<a class="btn btn-default btn-xs" href="<?php echo $this->url('teacher/delete-subject', array('id' => $subject['id'])) ?>">
								<span class="glyphicon glyphicon-trash"></span>
							</a>
						</div>
						<a class="btn btn-default btn-xs pull-right addSubsubject" href="<?php echo $this->url('teacher/add-subsubject', array('id' => $subject['id'])) ?>">
						<span class="glyphicon glyphicon-plus"></span>Lisa uus alamteema</a>
					</li>
					<div class="panel-body">
						<ul class="list-group subsubjects" id="subId<?php echo $subject['id'] ?>">
							<?php foreach ($subject['subsubjects'] as $subsubject): ?>
								<li class="list-group-item" id="subsubjectId<?php echo $subsubject['id'] ?>">
									<p class="subsubjectName pull-left">
										<?php echo $this->escapeHtml($subsubject['name']) ?>
									</p>
									<a class="btn btn-default btn-xs pull-left" href="<?php echo $this->url('teacher/delete-subsubject', array('id' => $subsubject['id'])) ?>">
										<span class="glyphicon glyphicon-trash"></span>
									</a>
									<a class="btn btn-default btn-xs pull-left editSubsubject" href="<?php echo $this->url('teacher/edit-subsubject', array('id' => $subsubject['id'])) ?>">
										<span class="glyphicon glyphicon-pencil"></span>
									</a>
									<?php if (empty($subsubject['homeworks'])) { ?>
										<a class="btn btn-default btn-xs pull-left addHomework" href="<?php echo $this->url('teacher/add-homework', array('subsubject_id' => $subsubject['id'])) ?>">
											<span class="glyphicon glyphicon-plus"></span>
											Lisa kodutöö
										</a>
									<?php } else { ?>
										<a class="btn btn-default btn-xs pull-left" href="<?php echo $this->url('teacher/homework', array('id' => array_values($subsubject['homeworks'])[0]->id)) ?>">
											Kodutöö eelvaade
										</a>
									<?php } ?>
									<div class="clearfix"></div>
									<ul class="list-group">
										<?php foreach ($subsubject['lessons'] as $lesson): ?>
											<li class="list-group-item">
												<a href="<?php echo $this->url('teacher/lesson', array('id' => $lesson->id)) ?>"><?php echo $lesson->name; ?></a>
												<a class="glyphicon glyphicon-trash pull-right" href="<?php echo $this->url('teacher/delete-lesson', array('id' => $lesson->id)) ?>">

												</a>
												<a class="glyphicon glyphicon-pencil pull-right" href="<?php echo $this->url('teacher/edit-lesson', array('id' => $lesson->id)) ?>">

												</a>
											</li>
										<?php endforeach; ?>
										<br>
										<a class="row btn btn-default btn-xs pull-right" href="<?php echo $this->url('teacher/add-lesson', array('id' => $subsubject['id'])) ?>">
										<span class="glyphicon glyphicon-plus"></span>Lisa uus tund</a>
									</ul>
								</li><!-- subsubject end -->
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endforeach; ?>
			</ul>
		</div><!-- bottom panel -->
	</div><!--  left col  -->
</div>
