<div class="panel-group col-md-4">
	<ul class="list-group">
		<li class="list-group-item">
			<a class="changeManageContent" href="my-course">Kursuse Sisu</a>
		</li>
		<li class="list-group-item">
			<a class="changeManageContent" href="homeworks">Esitatud kodutööd</a>
		</li>
		<li class="list-group-item">
			<a class="changeManageContent" href="students">Kes on kursusel</a>
		</li>
	</ul>
</div>