<?php
	$this->headTitle('Unustasid parooli - ');
?>
<h1>Unustasid parooli?</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('register/forgotten-password'));
	$form->prepare();

	echo $this->form()->openTag($form);
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>