<?php
	$this->headTitle('Registreeri - ');
?>
<h1>Registreeri</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('register'));
	$form->prepare();

	echo $this->form()->openTag($form);
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('firstname')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('lastname')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('password_confirm')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('captcha')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>