
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('categories', array('action' => 'edit-ajax', 'id' => $this->category->getId())));
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="alert flash-message">
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('name')); ?>
    <div class="col-sm-6">
        <?php echo $this->formElement($form->get('name')->setValue($this->category->getName())); ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('order')); ?>
    <div class="col-sm-2">
        <?php echo $this->formElement($form->get('order')->setValue((int)$this->category->getOrder())); ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('status')); ?>
    <div class="col-sm-1 pull-left">
        <?php echo $this->formElement($form->get('status')->setValue($this->category->getStatus())); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
        <?php echo $this->formButton($form->get('submit')->setAttribute('onclick', 'silmaring.postAjaxForm("'.$this->url('categories', array('action' => 'edit-ajax', 'id' => $this->category->getId())).'","#editForm", true)'), $this->translate('Update')); ?>
    </div>
    <div class="col-sm-3 pull-right">
        <a class="btn btn-lg btn-danger pull-right" href="<?php echo $this->url('categories', array('action' => 'delete', 'id' => $this->category->getId())); ?>" onclick="if(confirm('<?php echo $this->translate('Are your sure?'); ?>'))return true; else return false;"><?php echo $this->translate("Delete"); ?></a>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
