<?php
$form = $this->form;
$form->setAttribute('action', $this->url('categories', array('action' => 'import-ajax')));
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="alert flash-message">
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('file')); ?>
    <div class="col-sm-1 pull-left">
        <?php echo $this->formElement($form->get('file')); ?>
    </div>
</div>
<div class="text-center loads" style="display: none;"><img src="<?php echo $this->url('home'); ?>images/ajax-loader.gif" alt="" /></div>
<div class="progress" style="display:none;">
    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
        0%
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
        <?php echo $this->formButton($form->get('submit'), $this->translate('Import')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script>
    $(function(){
        silmaring.postAjaxFormWithFile('<?php echo $this->url('categories', array('action' => 'import-ajax')); ?>', '#importForm', true);
    });
</script>
