<div class="jumbotron">
    <h1>Tere tulemast Silmaringi Eksamikeskkonda!</h1>
    <p>Eksamikeskkond võimaldab Sinul valmistuda paremini riigieksamiteks. See on 100% veebikursus, kõik olulised teemad saavad kaetud, tasemel õpetajad kes teevad materjali teile lihtsaks ja selgeks.</p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Mõnusaim viis, kuidas õppida</h3>
            </div>
            <div class="panel-body">
                <p>Lahenda ülesandeid seal, kus ise soovid - kodus, kohvikus või sõbra juures. Õpi hommikul, õhtul või laupäeval - nii, kuidas sulle meeldib.</p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank">Uuri veel</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tasemel õpetaja tagab edu</h3>
            </div>
            <div class="panel-body">
                <p>Sind juhendab Nõo Reaalgümnaasiumi matemaatikaõpetaja, kelle õpilased saavutavad pidevalt häid eksamitulemusi. Lahe värk.</p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank">Vaata lisa</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Vali endale mugav tempo</h3>
            </div>
            <div class="panel-body">
                <p>Kui saad teema kiiresti selgeks, võta järgmine. Kui mõte ei jookse, ära muretse, keegi halbu hindeid ei pane. Võta aega, süvene ja teeme asja selgeks. </p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Hakka pihta</a></p>
            </div>
        </div>
    </div>
</div>
