<?php
	$this->headTitle('Lisa uus kursus - ');
?>
<h1>Lisa uus kursus</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/add-course'));
	$form->prepare();

	echo $this->form()->openTag($form);

	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('name'));
	echo $this->formRow($form->get('price'));
	echo $this->formRow($form->get('published'));
	echo $this->formSubmit($form->get('submit'));

	echo $this->form()->closeTag();