<?php
	$this->headTitle('Kursus - ');
?>
<div class="row">
	<div class="col-md-5 pull-left">
		<h2><?php echo $this->escapeHtml($courseData['course']->name) ?></h2>
	</div>
</div>
<div class="row">
	<?php echo $this->sidebar ?>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title pull-left">Kirjeldus</h2>
				<div class="clearfix"></div>
			</div>
			<div class="panel-body" id="courseDescription">
				<p>
					<?php echo $courseData['course']->description ?>
				</p>
			</div>
		</div>
		<br>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title pull-left">Teemad</h2>
				<div class="clearfix"></div>
			</div>
			<ul class="list-group" id="subjects">
				<?php foreach ($courseData['subjects'] as $subject): ?>
					<li class="list-group-item active" id="subjectId<?php echo $subject['id'] ?>">
						<p class="subjectName"><?php echo $this->escapeHtml($subject['name']) ?></p>
					</li>
					<div class="panel-body">
						<ul class="list-group subsubjects" id="subId<?php echo $subject['id'] ?>">
							<?php foreach ($subject['subsubjects'] as $subsubject): ?>
								<li class="list-group-item" id="subsubjectId<?php echo $subsubject['id'] ?>">
									<p class="subsubjectName pull-left">
										<b><?php echo $this->escapeHtml($subsubject['name']) ?></b>
									</p>
									<div class="clearfix"></div>
									<ul class="list-group">
										<?php foreach ($subsubject['lessons'] as $lesson): ?>
											<li class="list-group-item">
												<p><?php echo $lesson->name; ?></p>
											</li>
										<?php endforeach; ?>
										<br>
									</ul>
								</li><!-- subsubject end -->
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endforeach; ?>
			</ul>
		</div><!-- bottom panel -->
	</div><!--  left col  -->
</div>
