<?php
	$this->headTitle('Kursus - ');
?>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2><?php echo $this->escapeHtml($course->name) ?></h2>
	</div>
</div>
<div class="row">
	<?php echo $this->sidebar ?>
	<div class="col-md-8 pull-right">
		<p><?php echo $this->escapeHtml($course->description) ?></p>
		<a class="btn btn-primary btn-me" href="<?php echo $this->url('admin/change-course-visibility', array('id' => $course->id)) ?>">
			<?php if ($course->published == true) { ?>
					Tee nähtamatuks
			<?php } else { ?>
				Tee nähtavaks
			<?php }?>
		</a>
	</div>
</div>
