<?php
	$this->headTitle('Kursused - ');
?>
<h2 class="pull-left">Halda kursuseid</h2>
<a class="btn btn-primary btn-me pull-right" href="<?php echo $this->url('admin/add-course') ?>">
	<span class="glyphicon glyphicon-plus"></span>
	Lisa uus kursus
</a>
<div class="clearfix"></div>
<hr>
<div class="row">
	<?php foreach ($courses as $course) : ?>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><a href="<?php echo $this->url('admin/course', array('id' => $course->id)) ?>"><?php echo $this->escapeHtml($course->name) ?></a></h3>
				</div>
				<div class="panel-body">
						<p><b>Hind: </b><?php echo $this->escapeHtml($course->price) ?></p>
						<p><b>ID: </b><?php echo $this->escapeHtml($course->id) ?></p>
						<?php if ($course->published != true): ?>
							<p>Kursus on suletud.</p>
						<?php else: ?>
							<p>Kursus on avatud.</p>
						<?php endif; ?>
						<a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/edit-course', array('id' => $course->id)) ?>">
							<span class="glyphicon glyphicon-edit"></span>
							Muuda
						</a>
						<a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/delete-course', array('id' => $course->id)) ?>">
							<span class="glyphicon glyphicon-trash"></span>
							Kustuta
						</a>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
</div>