<?php
	$this->headTitle('Kursusel osalejad - ');
?>
<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Kursusel osalejad (<?php echo count($participants) ?>)</h2>
	</div>
	<div class="col-md-5 pull-right">
		<a class="btn btn-primary btn-me pull-right" href="<?php echo $this->url('admin/empty-course', array('id' => $id)) ?>">Tühjenda kursus</a>
	</div>
</div>
<div class="row">
	<table class="table table-striped">
		<tr>
			<td>Id</td>
			<td>Eesnimi</td>
			<td>Perekonnanimi</td>
			<td>E-mail</td>
			<td>Staatus</td>
			<td></td>
		</tr>
		<?php foreach ($participants as $student): ?>
		<tr>
			<td><?php echo $this->escapeHtml($student['user']->id) ?></td>
			<td><?php echo $this->escapeHtml($student['user']->firstname) ?></td>
			<td><?php echo $this->escapeHtml($student['user']->lastname) ?></td>
			<td><?php echo $this->escapeHtml($student['user']->email) ?></td>
			<?php if ($student['status'] == true) { ?>
				<td>Kasutajal on ligipääs kursusele</td>
				<td>
					<a href="<?php echo $this->url('admin/change-user-course-status', array('user_id' => $student['user']->id, 'course_id' => $id, 'status' => null)) ?>">
						Eemalda ligipääs kursuselt
					</a>
				</td>
			<?php } else { ?>
				<td>Kasutajal pole ligipääsu kursusele</td>
				<td>
					<a href="<?php echo $this->url('admin/change-user-course-status', array('user_id' => $student['user']->id, 'course_id' => $id, 'status' => true)) ?>">
						Anna ligipääs kursusele
					</a>
				</td>
			<?php } ?>
		</tr>
		<?php endforeach; ?>
	</table>
</div>