<?php
	$this->headTitle('Muuda kursust - ');
?>
<h1>Muuda kursust</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/edit-course', array('id' => $this->id)));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('price')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('published')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>