<?php
	$this->headTitle('Saada e-mail - ');
?>
<h1>Muuda kursust</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/send-email-to-user', array('user_id' => $this->user_id)));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('user_id'));
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('subject')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('body')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>