<div id="content">
    <?php if ($this->successMessages) : ?>
        <?php foreach ($this->successMessages as $message) : ?>
            <div class="alert alert-success">
                <?php echo $message; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <ul class="lesson_plan">
        <?php foreach($this->materials as $cid => $materialsArray) :?>
            <li>
                <h2 class="underline_title">
                    <?php $categoryPath = $this->getCategoryPath($this->allCategories, $cid); $categoryPath = array_reverse($categoryPath); ?>
                    <?php $i = 1; foreach($categoryPath as $category) : ?>
                        <?php if($i!=1) : ?> / <?php endif; ?>
                        <?php if($i==2) : ?><span class="semi_b"><?php endif; ?>
                        <?php if($i>2) : ?><span class="simple"><?php endif; ?>
                        <?php echo $category['c_name']; ?>
                        <?php if($i>2) : ?></span><?php endif; ?>
                        <?php if($i==2) : ?></span><?php endif; ?>
                        <?php $i++; endforeach; ?>
                </h2>
                <ol>
                    <?php foreach($materialsArray as $material) :?>
                        <?php if(!$this->uploads()->has($material['filename']) && $material['file_type']!='video' && $material['file_type']!='test' && $material['file_type']!='worksheet') continue; ?>
                        <?php $sentClasses = $this->em->getRepository('AmaMaterials\Entity\File')->findFilesSentToClasses($this->user, $material['file_id']); ?>
                        <?php
                        $target = 'target="_blank"';
                        $onclick = '';
                        if ( $material['file_type'] == 'image' || $material['file_type']=='file'  || $material['file_type']=='presentation' ) {
                            $url = $this->uploads()->get($material['filename']);
                            $ext = $url->getExtension();
                            if($material['file_type']=='image') {
                                $url = $this->htImgUrl($material['filename'], 'images1024x768');
                            }
                        }
                        else if($material['file_type']=='video') {
                            $url = $material['file_video'];
                        }
                        else if($material['file_type']=='test') {
                            $url = 'javascript:;';
                            $target = '';
                            $onclick = "onclick=\"silmaring.openInModal('".$this->url('manageTests', array('action' => 'edit', 'cid' => $cid, 'id' => $material['file_id']))."','modal-lg');\"";
                            if(count($sentClasses)>0 || $material['u_id']!=$material['lpfu_id']) {
                                $onclick = "onclick=\"silmaring.openInModal('".$this->url('manageTests', array('action' => 'no-edit', 'cid' => $cid, 'id' => $material['file_id']))."','modal-lg');\"";
                            }
                        }
                        else if($material['file_type']=='worksheet') {
                            $url = 'javascript:;';
                            $target = '';
                            $onclick = "onclick=\"silmaring.openInModal('".$this->url('manageWorksheets', array('action' => 'edit', 'cid' => $cid, 'id' => $material['file_id']))."','modal-lg');\"";
                            if(count($sentClasses)>0  || $material['u_id']!=$material['lpfu_id']) {
                                $onclick = "onclick=\"silmaring.openInModal('".$this->url('manageWorksheets', array('action' => 'no-edit', 'cid' => $cid, 'id' => $material['file_id']))."','modal-lg');\"";
                            }
                        }
                        ?>
                        <li><a href="<?php echo $url; ?>" <?=$target;?> <?=$onclick;?>><?php echo $material['name']; ?></a> <?php if($this->getIsNew($material['date_added']) && $this->user->hasRole('k_student')) : ?><span class="new_item">(<?php echo $this->translate('NEW'); ?>)</span><?php endif; ?></li>
                    <?php endforeach; ?>
                </ol>
                 <a href="<?php echo $this->url('lessonPlans', array('action' => 'category', 'id' => $cid)); ?>" class="btn btn-default"><?php echo $this->translate("View all"); ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>