<?php
	$this->headTitle('Logi sisse - ');
?>
<h1>Logi sisse</h1>
<?php echo $this->escapeHtml($this->messages); ?>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('home/login'));
	$form->prepare();

	echo $this->form()->openTag($form);
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>