<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AmaUsers\Form\ForgottenPasswordFilter'     => __DIR__ . '/src/AmaUsers/Form/ForgottenPasswordFilter.php',
  'AmaUsers\Form\SettingsFilter'              => __DIR__ . '/src/AmaUsers/Form/SettingsFilter.php',
  'AmaUsers\Form\LoginForm'                   => __DIR__ . '/src/AmaUsers/Form/LoginForm.php',
  'AmaUsers\Form\LoginFilter'                 => __DIR__ . '/src/AmaUsers/Form/LoginFilter.php',
  'AmaUsers\Form\RegisterFilter'              => __DIR__ . '/src/AmaUsers/Form/RegisterFilter.php',
  'AmaUsers\Form\RegisterForm'                => __DIR__ . '/src/AmaUsers/Form/RegisterForm.php',
  'AmaUsers\Form\SettingsForm'                => __DIR__ . '/src/AmaUsers/Form/SettingsForm.php',
  'AmaUsers\Form\ForgottenPasswordForm'       => __DIR__ . '/src/AmaUsers/Form/ForgottenPasswordForm.php',
  'AmaUsers\Entity\Repository\UserRepository' => __DIR__ . '/src/AmaUsers/Entity/Repository/UserRepository.php',
  'AmaUsers\Entity\Role'                      => __DIR__ . '/src/AmaUsers/Entity/Role.php',
  'AmaUsers\Entity\User'                      => __DIR__ . '/src/AmaUsers/Entity/User.php',
  'AmaUsers\Controller\IndexController'       => __DIR__ . '/src/AmaUsers/Controller/IndexController.php',
  'AmaUsers\Controller\SettingsController'    => __DIR__ . '/src/AmaUsers/Controller/SettingsController.php',
  'AmaUsers\Controller\RegisterController'    => __DIR__ . '/src/AmaUsers/Controller/RegisterController.php',
  'AmaUsers\Controller\DashboardController'   => __DIR__ . '/src/AmaUsers/Controller/DashboardController.php',
  'AmaUsers\Module'                           => __DIR__ . '/Module.php',
);
