<?php $this->headTitle($this->translate('Edit student')); ?>
    <header class="page-head clearfix">
        <h1><?php echo $this->translate("Edit student"); ?></h1>
    </header>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mySchools', array('action' => 'edit-student', 'id' => $this->school->getId(), 'tid' => $this->student->getId())));
$form->setAttribute('role', 'form');
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php if ($this->successMessages) : ?>
    <?php foreach ($this->successMessages as $message) : ?>
        <div class="alert alert-success">
            <?php echo $message; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($this->messages) : ?>
    <div class="alert alert-warning">
        <?php echo $this->messages; ?>
    </div>
<?php endif; ?>

<?php if ($this->errorMessages) : ?>
    <div class="alert alert-warning">
        <?php foreach ($this->errorMessages as $message) : ?>
            <?php echo $message; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if($this->student->getFirstStudentUser()) : ?>
    <div class="form-group">
        <strong><?php echo $this->translate("Connected username/e-email"); ?></strong> <?php echo $this->student->getFirstStudentUser()->getUser()->getEmail(); ?>
    </div>
<?php endif; ?>
    <div class="form-group">
        <?php echo $this->formElement($form->get('firstName')->setValue($this->student->getFirstName())); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formElement($form->get('lastname')->setValue($this->student->getLastname())); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formElement($form->get('personalCode')->setValue($this->student->getPersonalCode())); ?>
    </div>
    <div class="">
        <h5><?php echo $this->translate("Choose classes"); ?></h5>
        <ul class="class-list">
            <li>
                <ul>
                    <li>
                        <div class="checkbox">
                            <?php foreach ($this->classes as $class) : ?>
                                <label><input type="radio" name="studentClasses[]" value="<?php echo $class['sc_id']; ?>" <?php if(in_array($class['sc_id'], $this->chosenClasses)) : ?>checked<?php endif; ?>> <?php echo $class['sc_className']; ?></label>
                            <?php endforeach; ?>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="form-group text-right">
        <div class="col-sm-2">
            <?php echo $this->formButton($form->get('submit'), $this->translate('Update')); ?>
        </div>
    </div>
    <div class="text-center">&nbsp;<br>&nbsp;</div>
<?php echo $this->form()->closeTag(); ?>