<?php $this->headTitle($this->translate("My schools")); ?>
<header class="page-head clearfix">
    <h1><?php echo $this->translate("My schools"); ?></h1>
</header>
<?php if ($this->successMessages) : ?>
    <?php foreach ($this->successMessages as $message) : ?>
        <div class="alert alert-success">
            <?php echo $message; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<div class="table-responsive">
    <table class="table ajax-my-school-dt">
        <thead>
        <tr>
            <th><?php echo $this->translate('School name'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<div id="datapaginaton"></div>
<script>
    var dt_url = '<?php echo $this->url('mySchools',array('action' => 'page')); ?>?order=<?php echo $this->orderBy; ?>';
</script>