<?php $this->headTitle($this->translate('Settings')); ?>
<header class="page-head clearfix">
    <h1><?php echo $this->translate("Settings"); ?></h1>
</header>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mySchools', array('action' => 'manage', 'id' => $this->school->getId())));
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php if ($this->successMessages) : ?>
    <?php foreach ($this->successMessages as $message) : ?>
        <div class="alert alert-success">
            <?php echo $message; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($this->messages) : ?>
    <div class="alert alert-warning">
        <?php echo $this->messages; ?>
    </div>
<?php endif; ?>
<?php if (!empty($this->errorMessages)) : ?>
    <div class="alert alert-warning">
        <?php foreach ($this->errorMessages as $message) : ?>
            <?php echo $message; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
    <div class="row">
        <div class="col-sm-4">
            <ul class="class-list">
                <?php foreach ($this->school_classes as $class) : ?>
                    <li>
                        <ul>
                            <li>
                                <div class="checkbox">
                                    <?php foreach ($this->school_classes_letters as $letter) : ?>
                                        <label><input type="checkbox" name="schoolClasses[]" value="<?php echo $class; ?><?php echo $letter; ?>" <?php if(in_array($class.$letter, $this->chosenClasses)) : ?>checked<?php endif; ?>> <?php echo $class; ?><?php echo $letter; ?></label>
                                    <?php endforeach; ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
            <br>
            <div class="form-group">
                <div class="col-sm-offset-1 col-sm-7">
                    <?php echo $this->formButton($form->get('submit'), $this->translate('Update')); ?>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('name')); ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($form->get('name')->setValue($this->school->getName())); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('shortName')); ?>
                <div class="col-sm-4">
                    <?php echo $this->formElement($form->get('shortName')->setValue($this->school->getShortName())); ?>
                </div>
            </div>
        </div>
    </div>

<?php echo $this->form()->closeTag(); ?>
