<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('id', 'subsubjectForm');

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('subject_id'));

?>
<div class="input-group">
	<span class="input-group-addon">Nimi</span>
	<?php echo $this->formRow($form->get('name')); ?>
</div>
<br>
<div class="input-group">
	<a class="btn btn-default btn-sm" href="<?php echo $this->url('teacher/add-subsubject', array('id' => $subjectId)); ?>" id="submitSubsubjectForm">Lisa</a>
</div>
<?php echo $this->form()->closeTag(); ?>