<?php
	$form = $this->form;
	$form->setAttribute('id', 'form');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('course_id'));
	
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
	<a href="<?php echo $courseId ?>" id="submitSubjectForm">Lisa</a>
	<a href="<?php echo $courseId ?>" id="cancelSubjectAdding">Katkesta</a>
</div>
<?php echo $this->form()->closeTag(); ?>
