<?php
	$this->headTitle('Lisa uus tund - ');
?>
<h2>Lisa uus tund</h2>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('teacher/add-lesson', array('id' => $subsubjectId)));
	$form->setAttribute('enctype', 'multipart/form-data');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('subsubject_id'));
	echo $this->formHidden($form->get('user_id'));
?>
<div class="input-group">
	<span class="input-group-addon">Nimi</span>
	<?php echo $this->formRow($form->get('name')); ?>
</div>
<br>
<div class="input-group">
	<span class="input-group-addon">Sisu</span>
	<?php echo $this->formRow($form->get('content')); ?>
</div>
<br>
<div class="input-group">
	<span class="input-group-addon">Nähtavus</span>
	<?php echo $this->formRow($form->get('published')); ?>
</div>
<br>
<div class="input-group">
	<span class="input-group-addon">Tüüp</span>
	<?php echo $this->formRow($form->get('type')); ?>
</div>
<br>
<div id="lesson-upload">
	<div class="input-group" id="url-field">
		<span class="input-group-addon">Youtube url</span>
		<?php echo $this->formRow($form->get('url')); ?>
	</div>
	<div id="file-field">
		<label>Sobivad failitüübid: <span></span></label>
		<?php echo $this->formRow($form->get('fileupload')); ?>
	</div>
</div>
<br>
<div class="input-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>