<?php
	$this->headTitle('Lisa kodutöö - ');
?>
<h1>Lisa kodutöö</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('teacher/add-homework', array('subsubject_id' => $subsubjectId)));
	$form->setAttribute('enctype', 'multipart/form-data');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('user_id'));
	echo $this->formHidden($form->get('subsubject_id'));

?>
<div class="form-group">
	<?php echo $this->formRow($form->get('description')); ?>
</div>
<?php echo $this->formRow($form->get('fileupload')); ?>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>