<?php
	$this->headTitle('Lisa õpilase kodutööle tagasiside - ');
?>
<h1>Lisa õpilase kodutööle tagasiside</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('teacher/add-feedback', array('homework_id' => $homeworkId, 'user_id' => $userId)));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('homework_id'));
	echo $this->formHidden($form->get('user_id'));
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('feedback')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>