<?php
	$this->headTitle('Kursus - ');
?>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Teemad</h2>
	</div>
	<div class="col-md-5 pull-right">
		<a class="btn btn-primary btn-me pull-right" href="<?php echo $this->url('teacher/add-subject', array('id' => $course->id)) ?>">
			<span class="glyphicon glyphicon-plus"></span>
			Lisa uus teema
		</a>
	</div>
</div>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2><?php echo $this->escapeHtml($course->name) ?></h2>
	</div>
</div>
<div class="row">
	<div class="col-md-5 pull-left">
		<p><?php echo $this->escapeHtml($course->description) ?></p>
	</div>
</div>
