<?php
	$this->headTitle('Muuda Alateemat - ');
?>
<h1>Muuda Alateemat</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('teacher/edit-subsubject', array('id' => $this->id)));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('subject_id'));
?>

<div class="form-group">
	<?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>