<?php
	$this->headTitle('Muuda õpilase kodutööle antud tagasiside - ');
?>
<h1>Muuda õpilase kodutööle antud tagasiside</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('teacher/edit-feedback', array('id' => $feedbackId)));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('homework_id'));
	echo $this->formHidden($form->get('user_id'));
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('feedback')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>