<?php
	$this->headTitle('Kodutööd - ');
?>
<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Kodutööd</h2>
	</div>
</div>
<div class="row">
	<?php echo $this->sidebar ?>
	<div class="col-md-8">
		<?php foreach ($homeworks as $key => $homework) { ?>
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title pull-left">Alamteema <?php echo $this->escapeHtml($homework->subsubjectName) ?> kodutöö</h2>
				<div class="clearfix"></div>
			</div>
			<div class="panel-body" >
				<table class="table table-striped">
					<tr>
						<td>Õpilase eesnimi</td>
						<td>Õpilase perekonnanimi</td>
						<td>E-mail</td>
						<td>Kodutöö</td>
						<td>Tagasiside</td>
					</tr>
						<?php if (!empty($homeworkAnswers[$key])) {?>
							<?php foreach ($homeworkAnswers[$key] as $homeworkAnswer) { ?>
								<tr>
									<td><?php echo $this->escapeHtml($homeworkAnswer['user']->firstname) ?></td>
									<td><?php echo $this->escapeHtml($homeworkAnswer['user']->lastname) ?></td>
									<td><?php echo $this->escapeHtml($homeworkAnswer['user']->email) ?></td>
									<td><a href="<?php echo $this->escapeHtml($homeworkAnswer['answer']->url) ?>" target="_blank" download>Lae õpilase kodutöö alla</a></td>
									<td><?php echo $this->escapeHtml($homeworkAnswer['answer']->feedback) ?>
										<hr>
										<?php if (!empty($homeworkAnswer['answer']->feedback)) { ?>
											<a href="<?php echo $this->url('teacher/edit-feedback', array('id' => $homeworkAnswer['answer']->id)) ?>">Muuda tagasiside</a>
											<br>
											<a href="<?php echo $this->url('teacher/delete-feedback', array('id' => $homeworkAnswer['answer']->id)) ?>">Kustuta tagasiside</a>
										<?php } else { ?>
											<a href="<?php echo $this->url('teacher/add-feedback', array('homework_id' => $key, 'user_id' => $homeworkAnswer['user']->id)) ?>">Kirjuta õpilasele tagasiside</a>
										<?php } ?>
									</td>
								</tr>
							<?php } ?>
						<?php } ?>
					</table>
			</div>
		</div>
		<?php } ?>
	</div>
</div>