<?php
	$this->headTitle('Kodutööd - ');
?>
<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Kodutööd</h2>
	</div>
</div>
<div class="row">
	<?php foreach ($homeworks as $key => $homework) { ?>
		<h2>Alamteema <?php echo $this->escapeHtml($homework->subsubjectName) ?> kodutöö</h2>
		<table>
			<tr>
				<td>Õpilase eesnimi</td>
				<td>Õpilase perekonnanimi</td>
				<td>E-mail</td>
				<td>Kodutöö</td>
				<td>Tagasiside</td>
				<td></td>
			</tr>
			<?php foreach ($homeworkAnswers[$key] as $homeworkAnswer) { ?>
				<tr>
					<td><?php echo $this->escapeHtml($homeworkAnswer['user']->firstname) ?></td>
					<td><?php echo $this->escapeHtml($homeworkAnswer['user']->lastname) ?></td>
					<td><?php echo $this->escapeHtml($homeworkAnswer['user']->email) ?></td>
					<td><a href="<?php echo $this->escapeHtml($homeworkAnswer['answer']->url) ?>" target="_blank" download>Lae õpilase kodutöö alla</a></td>
					<td><?php echo $this->escapeHtml($homeworkAnswer['answer']->feedback) ?></td>
					<td>
						<?php if (!empty($homeworkAnswer['answer']->feedback)) { ?>
							<a href="<?php echo $this->url('teacher/edit-feedback', array('id' => $homeworkAnswer['answer']->id)) ?>">Muuda õpilasele antud tagasiside</a>
							<a href="<?php echo $this->url('teacher/delete-feedback', array('id' => $homeworkAnswer['answer']->id)) ?>">Kustuta õpilasele antud tagasiside</a>
						<?php } else { ?>
							<a href="<?php echo $this->url('teacher/add-feedback', array('homework_id' => $key, 'user_id' => $homeworkAnswer['user']->id)) ?>">Kirjuta õpilasele tagasiside</a>
						<?php } ?>
					</td>
				</tr>
			<?php } ?>
		</table>
	<?php } ?>
</div>