<div class="panel panel-default">
	<div class="panel-heading">
		<h2 class="panel-title"><?php echo $this->escapeHtml($lesson->name) ?></h2>
		<div class="clearfix"></div>
	</div>
	<div class="panel-body">
		<p class="well"><?php echo $this->escapeHtml($lesson->content) ?></p>
			<?php if ($lesson->type == 'images') { ?>
			<?php 
				$lessonFilesArray = array(); 
				foreach ($lessonFiles as $lessonFile){
					$lessonFilesArray[] = $lessonFile;
				}
			?>
			<div id="carousel-wrapper" style="min-height: 450px">
				<div id="carousel">
					<?php foreach ($lessonFilesArray as $lessonFile) { ?>
						<img src="<?php echo $this->escapeHtml($lessonFile->url) ?>" alt="<?php echo $this->escapeHtml($lesson->name) ?>" />
					<?php } ?>
				</div>
			</div>
			<div id="pager-wrapper">
				<div id="pager">
					<?php foreach ($lessonFilesArray as $lessonFile) { ?>
						<img src="<?php echo $this->escapeHtml($lessonFile->url) ?>" class="page" alt="<?php echo $this->escapeHtml($lesson->name) ?>" width="auto" height="80px" />
					<?php } ?>
				</div>
			</div>
			<?php } else if ($lesson->type == 'audio') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<audio controls>
						<source src="<?php echo $this->escapeHtml($lessonFile->url) ?>" type="audio/mpeg">
					</audio>
				<?php } ?>
			<?php } else if ($lesson->type == 'presentation') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<iframe src="<?php echo $this->escapeHtml($lessonFile->url) ?>" width="100%" height="800px"></iframe>
				<?php } ?>
			<?php } else if ($lesson->type == 'video') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<iframe width="100%" height="500px" src="<?php echo $this->escapeHtml(preg_replace('/watch\?v=/', 'embed/', $lessonFile->url)) ?>" frameborder="0" allowfullscreen></iframe>
				<?php } ?>
			<?php } ?>
	</div>
</div>

<?php echo $this->headScript()->prependFile($this->basePath() . '/js/slideShow.js'); ?>
