<?php
	$this->headTitle('Kursus - ');
?>

<div class="row">
	<div class="col-md-5 pull-right">
		<a class="btn btn-primary btn-me pull-right" href="<?php echo $this->url('teacher/add-subject', array('id' => $course->id)) ?>">
			<span class="glyphicon glyphicon-plus"></span>
			Lisa uus teema
		</a>
	</div>
</div>
<div class="row">
	<div class="col-md-5 pull-left">
		<h2><?php echo $this->escapeHtml($course->name) ?></h2>
	</div>
</div>
<div class="row">
	<div class="col-md-5 pull-left">
		<p><?php echo $this->escapeHtml($course->description) ?></p>
	</div>
</div>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading"><h2 class="panel-title">Teemad</h2></div>
		<ul class="list-group">
		<?php foreach ($subjects as $subject) : ?>
		<li class="list-group-item active"><?php echo $this->escapeHtml($subject->name). " #" .$this->escapeHtml($subject->id) ?>
			<div class="btn-group pull-right" role="group" aria-label="...">
				<a class="btn btn-default btn-xs" href="<?php echo $this->url('teacher/edit-subject', array('id' => $subject->id)) ?>">
					<span class="glyphicon glyphicon-plus"></span>Muuda teemat
				</a>
				<a class="btn btn-default btn-xs" href="<?php echo $this->url('teacher/delete-subject', array('id' => $subject->id)) ?>">
					<span class="glyphicon glyphicon-trash"></span>Kustuta teema
				</a>
			</div>
		</li>
		<div class="panel-body">
			<ul class="list-group">
				<?php foreach ($subsubjectTable->getSubsubjectsBySubjectId($subject->id) as $subsubject) : ?>
				<li class="list-group-item">
					<?php echo $this->escapeHtml($subsubject->name) ?>
					<a class="glyphicon glyphicon-trash pull-right" href="<?php echo $this->url('teacher/delete-subsubject', array('id' => $subsubject->id)) ?>"></a>
				</li>
				<?php endforeach; ?>
			</ul>
			<a class="btn btn-default btn-xs pull-right" href="<?php echo $this->url('teacher/add-subsubject', array('id' => $subject->id)) ?>">
			<span class="glyphicon glyphicon-plus"></span>Lisa uus alamteema</a>
			
		</div>
		<?php endforeach; ?>
		</ul>
</div>
