<?php
	$this->headTitle('Kursus - ');
?>
<div class="row">
	<div class="col-md-5 pull-left">
		<h2><?php echo $this->escapeHtml($course->name) ?></h2>
	</div>
</div>
<div class="row">
	<div class="col-md-5 pull-left">
		<p><?php echo $this->escapeHtml($course->description) ?></p>
	</div>
</div>
<div class="row">
	<?php echo $this->sidebar ?>

	<div class="panel panel-primary col-md-8">
		<div class="row">
			<a class="btn btn-primary btn-me pull-right" id="addSubject" href="<?php echo $this->url('teacher/add-subject', array('id' => $course->id)) ?>">
				<span class="glyphicon glyphicon-plus"></span>
				Lisa uus teema
			</a>
		</div>
		<div class="panel-heading"><h2 class="panel-title">Teemad</h2></div>
		<ul class="list-group" id="subjects">
			<?php foreach ($subjects as $subject) : ?>
				<li class="list-group-item active" id="subjectId<?php echo $subject->id ?>">
					<p class="subjectName"><?php echo $this->escapeHtml($subject->name) ?></p>
					<div class="btn-group" role="group" aria-label="...">
						<a class="btn btn-default btn-xs editSubject" href="<?php echo $this->url('teacher/edit-subject', array('id' => $subject->id)) ?>">
							<span class="glyphicon glyphicon-pencil"></span>
						</a>
						<a class="btn btn-default btn-xs" href="<?php echo $this->url('teacher/delete-subject', array('id' => $subject->id)) ?>">
							<span class="glyphicon glyphicon-trash"></span>
						</a>
					</div>
				</li>
				<div class="panel-body">
					<ul class="list-group">
						<?php foreach ($subsubjectTable->getSubsubjectsBySubjectId($subject->id) as $subsubject) : ?>
							<li class="list-group-item">
								<?php echo $this->escapeHtml($subsubject->name) ?>
								<a class="glyphicon glyphicon-trash pull-right" href="<?php echo $this->url('teacher/delete-subsubject', array('id' => $subsubject->id)) ?>"></a>
								<a class="btn btn-default btn-xs pull-right" href="<?php echo $this->url('teacher/edit-subsubject', array('id' => $subsubject->id)) ?>">
									<span class="glyphicon glyphicon-plus"></span>Muuda alateemat
								</a>
								<ul class="list-group">
									<?php foreach ($lessonTable->getLessonsBySubsubjectId($subsubject->id) as $lesson) : ?>
										<li class="list-group-item">
											<?php echo $lesson->name; ?>
											<a class="glyphicon glyphicon-trash pull-right" href="<?php echo $this->url('teacher/delete-lesson', array('id' => $lesson->id)) ?>"></a>
											<a class="btn btn-default btn-xs pull-right" href="<?php echo $this->url('teacher/edit-lesson', array('id' => $lesson->id)) ?>">
												<span class="glyphicon glyphicon-plus"></span>Muuda tundi
											</a>
										</li>
									<?php endforeach; ?>
									<a class="row btn btn-default btn-xs pull-right" href="<?php echo $this->url('teacher/add-lesson', array('id' => $subsubject->id)) ?>">
									<span class="glyphicon glyphicon-plus"></span>Lisa uus tund</a>
								</ul>
							</li>
						<?php endforeach; ?>
					</ul>
					<a class="btn btn-default btn-xs pull-right" href="<?php echo $this->url('teacher/add-subsubject', array('id' => $subject->id)) ?>">
					<span class="glyphicon glyphicon-plus"></span>Lisa uus alamteema</a>
					
				</div>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
