<?php
	$this->headTitle('Saada e-mail - ');
?>
<h1>Saada e-mail</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('teacher/send-email-to-all-participants', array('course_id' => $this->course_id, 'teacher_id' => $this->teacher_id)));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('course_id'));
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('subject')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('body')); ?>
</div>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>