<?php
	$this->headTitle('Õpilased - ');
?>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Minu õpilased</h2>
	</div>
</div>
<div class="row">
	<table class="table table-striped">
		<tr>
			<td>Eesnimi</td>
			<td>Perekonnanimi</td>
			<td>E-mail</td>
		</tr>
	<?php foreach ($students as $student): ?>
		<?php if ($student['status'] == true) { ?>
			<tr>
				<td><?php echo $this->escapeHtml($student['data']->firstname) ?></td>
				<td><?php echo $this->escapeHtml($student['data']->lastname) ?></td>
				<td><?php echo $this->escapeHtml($student['data']->email) ?></td>
			</tr>
		<?php } ?>
	<?php endforeach; ?>
	</table>
</div>