<?php
	$this->headTitle('Õpilased - ');
?>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Minu õpilased</h2>
	</div>
</div>
<div class="row">
	<?php echo $this->sidebar ?>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title pull-left">Osalejad</h2>
				<div class="clearfix"></div>
			</div>
			<table class="table table-striped">
				<tr>
					<td>Eesnimi</td>
					<td>Perekonnanimi</td>
					<td></td>
					<td><a class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('teacher/send-email-to-all-participants', array('course_id' => $courseId,'teacher_id' => $teacherId)) ?>">Saada kõigile kiri</a></td>
				</tr>
				<?php if (!empty($students)) { ?>
					<?php foreach ($students as $student): ?>
						<?php if ($student['status'] == true) { ?>
							<tr>
								<td><?php echo $this->escapeHtml($student['data']->firstname) ?></td>
								<td><?php echo $this->escapeHtml($student['data']->lastname) ?></td>
								<td></td>
								<td><a class="btn btn-default btn-sm pull-right"
									href="<?php echo $this->url('teacher/send-email-to-user', array('user_id' => $student['data']->id,'teacher_id' => $teacherId)) ?>">Saada kiri</a></td>
							</tr>
						<?php } ?>
					<?php endforeach; ?>
				<?php } ?>
			</table>
		</div>
	</div>

</div>