<?php $this->headTitle($this->translate("Sign up")); ?>
<a href="<?php echo $this->url('home'); ?>" id="register" class="btn btn-primary" type="submit"><?php echo $this->translate('Sign in'); ?></a>
<div id="vCenter">
<div class="text-center">
    <a href="<?php echo $this->url('home'); ?>" id="site-logo"><img src="<?php echo $this->url('home'); ?>images/logo.jpg"></a>
</div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home'));
$form->setAttribute('class', 'form-signin');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formElement($form->get('csrf'));
?>
<div class="alert alert-warning flash-message"></div>
<div class="loading"><img src="<?php echo $this->url('home'); ?>images/ajax-loader.gif" alt="" /></div>
<div class="form-group">
    <?php echo $this->formElement($form->get('role')); ?>
</div>
<div class="form-group">
    <?php echo $this->formElement($form->get('email')); ?>
</div>
<div class="form-group">
    <?php echo $this->formElement($form->get('first_name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formElement($form->get('lastname')); ?>
</div>
<div class="form-group text-center col-md-10 col-md-offset-1">
    <?php echo $this->formButton($form->get('submit')->setAttribute('onclick', 'silmaring.postAjaxForm("'.$this->url('registerAjax').'","#registerForm")'), $this->translate('Sign up'));  ?>
</div>
<div class="form-group text-center col-md-10 col-md-offset-1">
    <a href="<?php echo $this->facebookLoginUrl; ?>" class="btn btn-primary"><?php echo $this->translate('Sign up with facebook'); ?></a>
</div>
<div class="form-group text-center col-md-10 col-md-offset-1">
    <a href="<?php echo $this->googleLoginUrl; ?>" class="btn btn-primary"><?php echo $this->translate('Sign up with google'); ?></a>
</div>
<div class="text-center">&nbsp;<br>&nbsp;</div>
<?php echo $this->form()->closeTag();?>
</div>
