<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate("Add material"); ?> +</button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('images', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate("Image"); ?></a></li>
        <li><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('files', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate("File"); ?></a></li>
        <li><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('presentations', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate("Presentation"); ?></a></li>
        <li><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('videos', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate("Video"); ?></a></li>
        <li><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('manageWorksheets', array('action' => 'add', 'cid' => $this->category->getId())); ?>','modal-lg')"><?php echo $this->translate("Worksheet"); ?></a></li>
        <li><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('manageTests', array('action' => 'add', 'cid' => $this->category->getId())); ?>','modal-lg')"><?php echo $this->translate("Test"); ?></a></li>
    </ul>
</div>