<h2 class="block-title"><?php echo $this->translate("All materials"); ?></h2>
<div class="all_filetypes">
    <div class="row">
        <div class="col-sm-4">
            <i class="type-ico type-file"></i>
            <div class="wrap">
                <h4><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('files', array('action' => 'select', 'cid' => $this->category->getId(), 'id' => '0')); ?>', 'modal-lg')"><?php echo $this->translate('Text files'); ?></a><span class="item_count">(<?php echo (int)$this->materialsCount['filesCount'];?>)</span></h4>
                <?php if(!$this->isParentCategory) : ?><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('files', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate('Add new'); ?> +</a><?php endif; ?>
            </div>
        </div>
        <div class="col-sm-4">
            <i class="type-ico type-image"></i>
            <div class="wrap">
                <h4><a  href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('images', array('action' => 'select', 'cid' => $this->category->getId(), 'id' => '0')); ?>', 'modal-lg')"><?php echo $this->translate('Images'); ?></a><span class="item_count">(<?php echo (int)$this->materialsCount['imagesCount'];?>)</span></h4>
                <?php if(!$this->isParentCategory) : ?><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('images', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate('Add new'); ?> +</a><?php endif; ?>
            </div>
        </div>
        <div class="col-sm-4">
            <i class="type-ico type-video"></i>
            <div class="wrap">
                <h4><a  href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('videos', array('action' => 'select', 'cid' => $this->category->getId(), 'id' => '0')); ?>', 'modal-lg')"><?php echo $this->translate('Videos'); ?></a><span class="item_count">(<?php echo (int)$this->materialsCount['videosCount'];?>)</span></h4>
                <?php if(!$this->isParentCategory) : ?><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('videos', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate('Add new'); ?> +</a><?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <i class="type-ico type-presentation"></i>
            <div class="wrap">
                <h4><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('presentations', array('action' => 'select', 'cid' => $this->category->getId(), 'id' => '0')); ?>', 'modal-lg')"><?php echo $this->translate('Presentations'); ?></a><span class="item_count">(<?php echo (int)$this->materialsCount['presentationsCount'];?>)</span></h4>
                <?php if(!$this->isParentCategory) : ?><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('presentations', array('action' => 'add', 'cid' => $this->category->getId())); ?>')"><?php echo $this->translate('Add new'); ?> +</a><?php endif; ?>
            </div>
        </div>
        <div class="col-sm-4">
            <i class="type-ico type-test"></i>
            <div class="wrap">
                <h4><a  href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('tests', array('action' => 'select', 'id' => $this->category->getId(), 'page' => '0')); ?>', 'modal-lg')"><?php echo $this->translate('Tests'); ?></a><span class="item_count">(<?php echo (int)$this->materialsCount['testsCount'];?>)</span></h4>
                <?php if(!$this->isParentCategory) : ?><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('manageTests', array('action' => 'add', 'cid' => $this->category->getId())); ?>','modal-lg')"><?php echo $this->translate('Add new'); ?> +</a><?php endif; ?>
            </div>
        </div>
        <div class="col-sm-4">
            <i class="type-ico type-worksheet"></i>
            <div class="wrap">
                <h4><a  href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('worksheets', array('action' => 'select', 'id' => $this->category->getId(), 'page' => '0')); ?>', 'modal-lg')"><?php echo $this->translate('Worksheets'); ?></a><span class="item_count">(<?php echo (int)$this->materialsCount['worksheetsCount'];?>)</span></h4>
                <?php if(!$this->isParentCategory) : ?><a href="javascript:;" onclick="silmaring.openInModal('<?php echo $this->url('manageWorksheets', array('action' => 'add', 'cid' => $this->category->getId())); ?>','modal-lg')"><?php echo $this->translate('Add new'); ?> +</a><?php endif; ?>
            </div>
        </div>
    </div>
</div>