<?php
$form = $this->form;
$form->setAttribute('action', $this->url('videos', array('action' => 'add-ajax', 'cid' => $this->category->getId())));
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="alert flash-message">
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('name')); ?>
    <div class="col-sm-6">
        <?php echo $this->formElement($form->get('name')); ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('description')); ?>
    <div class="col-sm-6">
        <?php echo $this->formElement($form->get('description')); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $this->formLabel($form->get('video')); ?>
    <div class="col-sm-6">
        <?php echo $this->formElement($form->get('video')); ?>
        <div class="help-block small"><?php echo $this->translate('Youtube url'); ?></div>
    </div>
</div>
<div class="progress" style="display:none;">
    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
        0%
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
        <?php echo $this->formButton($form->get('submit'), $this->translate('Add')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script>
    $(function(){
        silmaring.postAjaxFormWithFile('<?php echo $this->url('videos', array('action' => 'add-ajax', 'cid' => $this->category->getId())); ?>', '#addForm', true);
    });
</script>
