<?php
	$this->headTitle('Esita kodutöö - ');
?>
<h1>Esita kodutöö</h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('student/add-homework-answer', array('id' => $id)));
	$form->setAttribute('enctype', 'multipart/form-data');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('user_id'));
	echo $this->formHidden($form->get('homework_id'));

?>
<?php echo $this->formRow($form->get('fileupload')); ?>
<div class="form-group">
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>