<?php
	$form = $this->form;
	$form->setAttribute('id', 'addNoteForm');
	$form->setAttribute('class', 'well');
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('lesson_id'));
	echo $this->formHidden($form->get('user_id'));
?>
<div class="input-group">
	<span class="input-group-addon">Märkme sisu</span>
	<?php echo $this->formRow($form->get('content')); ?>
</div>
<br>
<div class="input-group">
	<a class="btn btn-default btn-sm" href="<?php echo $this->url('student/add-note', array('lesson_id' => $lessonId)) ?>" id="submitAddNoteForm">Lisa</a>
</div>
<?php echo $this->form()->closeTag(); ?>