<?php
	$this->headTitle('Kursused - ');
?>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Kõik kursused</h2>
	</div>
</div>
<div class="row">
	<?php foreach ($courses as $course) : ?>
		<?php if ($course['course'] ->published == true): ?>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<a href="<?php echo $this->url('student/course', array('id' => $course['course']->id)) ?>"><?php echo $this->escapeHtml($course['course']->name) ?></a>
						</h3>
					</div>
					<div class="panel-body">
						<p class="well well-sm">
							<?php echo $course['course']->description ?>
						</p>
						<p>
							<?php if ($course['teacher']) { ?>
								<b>Õpetaja:</b> <?php echo $course['teacher']->firstname  . " " . $course['teacher']->lastname ?>
							<?php } else { ?>
								<span class="label label-danger">Õpetaja puudub</span>
							<?php } ?>
						</p>
						<p>
							<?php if ($course['hasBought']) { ?>
								</br><span class="label label-success">Kursus ostetud!</span>
							<?php } else { ?>
								<span class="label label-default"><?php echo $course['course']->price . " " . "€" ?></span>
							<?php } ?>
						</p>
					</div>
					<div class="panel-footer">
						<small>
							<?php
								$startDate = date("d.m.Y", strtotime($course['course']->start_date));
								echo $startDate. " - ";
								$endDate = date("d.m.Y", strtotime($course['course']->end_date));
								echo $endDate;

								if ((time()-(60*60*24)) > strtotime($endDate)) {
									echo '</br><span class="label label-danger">Kursus on läbi</span>';
								}
								else if ((time()-(60*60*24)) < strtotime($startDate)) {
									echo '</br><span class="label label-warning">Kursus pole veel alanud</span>';
								}								
							?>
						</small>
					</div>
				</div>
			</div>
		<?php endif; ?>
	<?php endforeach; ?>
</div>