<?php
	$this->headTitle('Kursused - ');
?>

<div class="row">
	<div class="col-md-5 pull-left">
		<h2>Kõik kursuseid</h2>
	</div>
</div>
<div class="row">
	<?php foreach ($courses as $course) : ?>
		<?php if ($course->published == true): ?>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><?php echo $this->escapeHtml($course->name) ?></h3>
					</div>
					<div class="panel-body">
						<p><b>Hind: </b><?php echo $this->escapeHtml($course->price) ?></p>
						<p><a href="<?php echo $this->url('student/buy-course', array('id' => $course->id)) ?>">Osta kursus</a></p>
					</div>
				</div>
			</div>
		<?php endif; ?>
	<?php endforeach; ?>
</div>