<?php
	$this->headTitle('Kõik märkmed - ');
?>
<div class="row">
		<h2>Vaatad kõiki märkmeid</h2>
</div>
<div class="row">
		<?php if (!empty($courses)) { ?>
			<?php foreach ($courses as $course) { ?>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Kursuse <b><?php echo $this->escapeHtml($course->name) ?></b> märkmed</h2>
				</div>
				<div class="panel-body">
				<?php if (!empty($course->subjects)) { ?>
					<?php foreach ($course->subjects as $subject) { ?>
						<h3>Teema: <?php echo $this->escapeHtml($subject->name) ?></h3>
						<hr>
						<?php if (!empty($subject->subsubjects)) { ?>
							<?php foreach ($subject->subsubjects as $subsubject) { ?>
								<div class="well">
								<p><b>Alamteema: <?php echo $this->escapeHtml($subsubject->name) ?></b></p>
								<hr>
								<?php if (!empty($subject->subsubjects)) { ?>
									<?php foreach ($subsubject->lessons as $lesson) { ?>
										<b><?php echo $this->escapeHtml($lesson->name) ?></b>
											<?php foreach ($lesson->notes as $note) { ?>
												<div class="alert alert-warning">
													<?php if (!empty($note)) { ?>
														<p><?php echo $this->escapeHtml($note->content) ?></p>
														<a class="btn btn-default btn-xs" href="<?php echo $this->url('student/edit-note', array('id' => $note->id)) ?>">
															<span class="glyphicon glyphicon-pencil"></span>
														</a>
														<a class="btn btn-default btn-xs" href="<?php echo $this->url('student/delete-note', array('id' => $note->id)) ?>">
															<span class="glyphicon glyphicon-trash"></span>
														</a>
													<?php } ?>
												</div>
											<?php } ?>
									<?php } ?>
								<?php } ?>
								</div>
							<?php } ?>
						<?php } ?>
					<?php } ?>
					</div>
				<?php } ?>
				</div>
			<?php } ?>
		<?php } ?>
</div>