<div class="panel panel-default">
	<div class="panel-heading">
		<h2 class="panel-title"><?php echo $this->escapeHtml($lesson->name) ?></h2>
		<div class="clearfix"></div>
	</div>
	<div class="panel-body">
		<p class="well"><?php echo $this->escapeHtml($lesson->content) ?></p>
			<?php if ($lesson->type == 'images') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<img src="<?php echo $this->escapeHtml($lessonFile->url) ?>" alt="<?php echo $this->escapeHtml($lesson->name) ?>" />
				<?php } ?>
			<?php } else if ($lesson->type == 'audio') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<audio controls>
						<source src="<?php echo $this->escapeHtml($lessonFile->url) ?>" type="audio/mpeg">
					</audio>
				<?php } ?>
			<?php } else if ($lesson->type == 'presentation') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<iframe src="<?php echo $this->escapeHtml($lessonFile->url) ?>" width="100%" height="auto"></iframe>
				<?php } ?>
			<?php } else if ($lesson->type == 'video') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<iframe width="100%" height="500px" src="<?php echo $this->escapeHtml(preg_replace('/watch\?v=/', 'embed/', $lessonFile->url)) ?>" frameborder="0" allowfullscreen></iframe>
				<?php } ?>
			<?php } ?>
	</div>
</div>
