<div class="panel panel-default">
	<div class="panel-heading">
		<h2 class="panel-title"><?php echo $this->escapeHtml($lesson->name) ?></h2>
		<?php if (empty($isLessonMarkedDone)) { ?>
			<a class="mark-lesson-done" id="mark-lesson-done-<?php echo $lesson->id ?>"
				href="<?php echo $this->url('student/mark-lesson-done', array('id' => $lesson->id)) ?>">Märgi tehtuks</a>
		<?php } else { ?>
			<p>Tund on märgitud tehtuks!</p>
		<?php } ?>
		<div class="clearfix"></div>
	</div>
	<div class="panel-body">
		<p class="well"><?php echo $this->escapeHtml($lesson->content) ?></p>
			<?php if ($lesson->type == 'images') { ?>
			<?php 
				$lessonFilesArray = array(); 
				foreach ($lessonFiles as $lessonFile){
					$lessonFilesArray[] = $lessonFile;
				}
			?>
			<div id="carousel-wrapper">
				<div id="carousel">
					<?php foreach ($lessonFilesArray as $lessonFile) { ?>
						<img src="<?php echo $this->escapeHtml($lessonFile->url) ?>" alt="<?php echo $this->escapeHtml($lesson->name) ?>" />
					<?php } ?>
				</div>
			</div>
			<div id="pager-wrapper">
				<div id="pager">
					<?php foreach ($lessonFilesArray as $lessonFile) { ?>
						<img src="<?php echo $this->escapeHtml($lessonFile->url) ?>" class="page" alt="<?php echo $this->escapeHtml($lesson->name) ?>" width="auto" height="80px" />
					<?php } ?>
				</div>
			</div>
			<?php } else if ($lesson->type == 'audio') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<audio controls>
						<source src="<?php echo $this->escapeHtml($lessonFile->url) ?>" type="audio/mpeg">
					</audio>
				<?php } ?>
			<?php } else if ($lesson->type == 'presentation') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<iframe src="<?php echo $this->escapeHtml($lessonFile->url) ?>" width="100%" min-height="800px"></iframe>
				<?php } ?>
			<?php } else if ($lesson->type == 'video') { ?>
				<?php foreach ($lessonFiles as $lessonFile) { ?>
					<iframe class="embed-responsive-item" src="<?php echo $this->escapeHtml(preg_replace('/watch\?v=/', 'embed/', $lessonFile->url)) ?>" frameborder="0" allowfullscreen></iframe>
				<?php } ?>
			<?php } ?>

			<a class="btn btn-primary btn-sm pull-right new-note" href="<?php echo $this->url('student/add-note', array('lesson_id' => $lesson->id)) ?>">
				<span class="glyphicon glyphicon-plus"></span>Tee uusi märkmeid
			</a>
			<div class="clearfix"></div>
			<b>Märkmed:</b>
			<div class="panel panel-default">
				<div class="panel-body" id="notes">
					<?php if(!empty($notes)) { ?>
						<?php foreach ($notes as $note) { ?>
							<div class="alert alert-warning" id="note<?php echo  $note->id ?>">
								<p><?php echo $this->escapeHtml($note->content) ?></p>
								<a class="btn btn-default btn-xs edit-note" href="<?php echo $this->url('student/edit-note', array('id' => $note->id)) ?>">
									<span class="glyphicon glyphicon-pencil"></span>
								</a>
								<a class="btn btn-default btn-xs delete-note" href="<?php echo $this->url('student/delete-note', array('id' => $note->id)) ?>">
									<span class="glyphicon glyphicon-trash"></span>
								</a>
							</div>
						<?php }?>
					<?php } else { ?>
						<p class="well no-notes">Sellel tunnil märkmed puuduvad</p>
					<?php } ?>
				</div>
			</div>

	</div>
</div>

<?php echo $this->headScript()->prependFile($this->basePath() . '/js/slideShow.js'); ?>