<?php
$form = $this->form;
$form->setAttribute('action', $this->url('manageWorksheets', array('action' => 'edit')));
$form->setAttribute('role', 'form');
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-sm-12 clearfix">
        <div class="alert alert-warning">
            <?php if($worksheet->getUser()->getId()!=$this->user->getId()) :?>
                <?=$this->translate("You cannot edit or change this worksheet because you are not the author."); ?>
            <?php else : ?>
            <?=$this->translate("You cannot edit or change this worksheet because you have allready send it to a class."); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="form-title row">
    <div class="form-group">
        <div class="col-sm-12">
            <?= $this->formElement($form->get('name')->setValue($worksheet->getName())->setAttribute("disabled", "disabled")); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
        <div class="col-sm-12">
            <?= $this->formElement($form->get('description')->setValue($worksheet->getDescription())->setAttribute("disabled", "disabled")); ?>
        </div>
    </div>
</div>
<div id="visible-question-blocks" class="margin-top-10">
    <?php foreach($worksheet->getQuestions() as $qnr => $question) : ?>
        <?=$this->partial('ama-worksheets/partial/edit-question-disabled', array('form' => $form, 'question' => $question, 'qnr' => $qnr));?>
    <?php endforeach;s ?>
</div>
<div class="loading text-center"><img src="<?php echo $this->url('home'); ?>images/ajax-loader.gif" alt="" /></div>
<div class="alert flash-message margin-top-10">
</div>

<?php echo $this->form()->closeTag(); ?>

