<?php if ($this->pageCount && false) : ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
    Next &gt;
  </a>
<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>

<?php if ($this->pageCount): ?>
<ul class="pagination">
<?php if (isset($this->previous)): ?>
  <li><a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">&laquo;</a></li>
 <?php else: ?>
  <li class="disabled"><a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">&laquo;</a></li>
<?php endif; ?> 
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a></li>
  <?php else: ?>
     <li class="active"><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>
<?php if (isset($this->next)): ?>
  <li><a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">&raquo;</a></li>
  <?php else: ?>
  <li class="disabled"><a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">&raquo;</a></li>
<?php endif; ?>
</ul>
<?php endif; ?>