<?php $this->headTitle($this->translate("Users")); ?>
<header class="page-head clearfix">
    <h1><?php echo $this->translate("Users"); ?></h1>
</header>
<?php if ($this->successMessages) : ?>
    <?php foreach ($this->successMessages as $message) : ?>
        <div class="alert alert-success">
            <?php echo $message; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<form action="<?php echo $this->url('users',array('action' => 'delete')); ?>" method="post" id="list-form">
    <button class="btn btn-danger pull-right" type="submit" onclick="if(confirm('<?php echo $this->translate('Are your sure?'); ?>'))return true; else return false;"><?php echo $this->translate("Delete"); ?></button>
    <div class="table-responsive">
        <table class="table ajax-users-dt">
            <thead>
            <tr>
                <th>#</th>
                <th><?php echo $this->translate('Email'); ?></th>
                <th><?php echo $this->translate('First name'); ?></th>
                <th><?php echo $this->translate('Lastname'); ?></th>
                <th><?php echo $this->translate('Role'); ?></th>
                <th><?php echo $this->translate('Status'); ?></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div id="datapaginaton"></div>
</form>
<script>
    var dt_url = '<?php echo $this->url('users',array('action' => 'page')); ?>?order=<?php echo $this->orderBy; ?>';
</script>