<?php $this->headTitle($this->translate("Account settings")); ?>
<header class="page-head clearfix">
    <h1><?php echo $this->translate("Account settings"); ?></h1>
</header>
<div class="border-box pad-15">
    <div class="row">
        <div class="col-sm-8">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('settings'));
            $form->setAttribute('role', 'form');
            $form->setAttribute('enctype', 'multipart/form-data');
            $form->prepare();

            echo $this->form()->openTag($form);
            ?>
            <?php if ($this->successMessages) : ?>
                <?php foreach ($this->successMessages as $message) : ?>
                    <div class="alert alert-success">
                        <?php echo $message; ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($this->messages) : ?>
                <div class="alert alert-warning">
                    <?php echo $this->messages; ?>
                </div>
            <?php endif; ?>

            <?php if ($this->errorMessages) : ?>
                <div class="alert alert-warning">
                    <?php foreach ($this->errorMessages as $message) : ?>
                        <?php echo $message; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <?php echo $this->formElement($form->get('firstName')->setValue($this->user->getFirstName())); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('lastname')->setValue($this->user->getLastname())); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('email')->setValue($this->user->getEmail())); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('personalCode')->setValue($this->user->getPersonalCode())); ?>
                <div
                    class="help-block small"><?php echo $this->translate('Personal code should be filled only if u want to connect school with your profile'); ?></div>
            </div>
            <div class="form-group">
                <div class="pull-left">
                    <?php echo $this->formLabel($form->get('image')); ?>
                    <?php echo $this->formFile($form->get('image')); ?>
                </div>
                <div class="pull-right profile-image">
                    <?php if ($user->getImage()) : ?>
                        <img src="<?php echo $this->htImgUrl($user->getImage(), 'profile'); ?>" alt="image"/><br>
                        <a href="<?php echo $this->url('deleteProfileImage'); ?>"><?php echo $this->translate('Delete'); ?></a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="clearfix"></div>
            <br>
            <hr>
            <div class="form-group">
                <i><?php echo $this->translate('Here u can change your password.'); ?></i>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('currentPassword')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('newPassword')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('newPasswordConfirm')); ?>
            </div>
        </div>
        <div class="col-sm-4">
            <strong><?= $this->translate('Choose what classes to display'); ?></strong>
            <ul class="class-list">
                <?php foreach ($this->categoryTree as $category) : ?>
                    <li id="c<?=$category['c_id']?>">
                        <div class="checkbox"><label><input type="checkbox" name="categories[]"
                                                            value="<?= $category['c_id'] ?>"
                                                            onclick="silmaring.changeCategoryTreeState($(this))"
                                                            data-parent="0"
                                                            <?=(!$this->userCategories?'checked':(in_array($category['c_id'], $this->userCategories)?'checked':''))?>> <?= $category['c_name'] ?></label></div>
                        <?php if ($category['subs']) : ?>
                            <?= $this->partial('ama-users/partial/category-tree-sub', array('categoryTree' => $category['subs'],'userCategories' => $this->userCategories)) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<div class="clearfix"></div>
    <div class="form-group">
        <?php echo $this->formButton($form->get('submit'), $this->translate('Update')); ?>
    </div>
    <div class="text-center">&nbsp;<br>&nbsp;</div>
    <?php echo $this->form()->closeTag(); ?>
</div>